In [53]:
import pandas as pd

In [54]:
air_quality_url = "https://raw.githubusercontent.com/timothyfraser/nyc_congestion_rep/refs/heads/main/data/aqi.csv"

In [55]:
aqi = pd.read_csv(air_quality_url)

aqi.head()

,lat,lon,datetime,param,concentration,unit,aqi,category,site_name,site_agency,aqs_id,aqs_id_full
0,39.922516,-75.186783,2025-05-06T04:00:00Z,PM2.5,5.6,UG/M3,31,1,RIT,Philadelphia Air Management Services,421010055,840421010055
1,39.960300,-75.142400,2025-05-06T04:00:00Z,PM2.5,5.1,UG/M3,28,1,FAB,Philadelphia Air Management Services,421010057,840421010057
2,39.923969,-75.122314,2025-05-06T04:00:00Z,PM2.5,5.0,UG/M3,28,1,South Camden,New Jersey Dept. of Environmental Protection,340070010,840340070010
3,39.991389,-75.080833,2025-05-06T04:00:00Z,PM2.5,4.1,UG/M3,23,1,NEW,Philadelphia Air Management Services,421010048,840421010048
4,40.924606,-75.067825,2025-05-06T04:00:00Z,PM2.5,1.3,UG/M3,7,1,Columbia,New Jersey Dept. of Environmental Protection,340410007,840340410007

In [56]:
aqi['site_agency'].value_counts()

New York Dept. of Environmental Conservation                271126
New Jersey Dept. of Environmental Protection                266233
Connecticut Dept. of Energy and Environmental Protection     98258
Philadelphia Air Management Services                         48741
Name: site_agency, dtype: int64

In [57]:
aqi_nyc = aqi[aqi['site_agency'] == 'New York Dept. of Environmental Conservation']

aqi_nyc

,lat,lon,datetime,param,concentration,unit,aqi,category,site_name,site_agency,aqs_id,aqs_id_full
14,40.580200,-74.199400,2025-05-06T04:00:00Z,PM2.5,6.5,UG/M3,36,1,Fresh Kills,New York Dept. of Environmental Conservation,360850111,840360850111
17,40.633060,-74.137156,2025-05-06T04:00:00Z,PM2.5,0.4,UG/M3,2,1,Port Richmond,New York Dept. of Environmental Conservation,840360850055,840360850055
19,41.182079,-74.028191,2025-05-06T04:00:00Z,PM2.5,0.0,UG/M3,0,1,Rockland Cty,New York Dept. of Environmental Conservation,360870005,840360870005
20,40.641819,-74.018707,2025-05-06T04:00:00Z,PM2.5,10.9,UG/M3,54,2,Bklyn - PS 314,New York Dept. of Environmental Conservation,360470052,840360470052
21,41.499400,-74.009700,2025-05-06T04:00:00Z,PM2.5,0.0,UG/M3,0,1,Newburgh,New York Dept. of Environmental Conservation,360710002,840360710002
...,...,...,...,...,...,...,...,...,...,...,...,...
684325,40.737500,-73.824400,2019-06-01T02:00:00Z,PM2.5,8.7,UG/M3,48,1,Queens,New York Dept. of Environmental Conservation,360810124,840360810124
684338,40.816101,-73.902199,2019-06-01T03:00:00Z,PM2.5,15.1,UG/M3,62,2,Bronx - IS52,New York Dept. of Environmental Conservation,360050110,840360050110
684339,40.737500,-73.824400,2019-06-01T03:00:00Z,PM2.5,9.3,UG/M3,51,2,Queens,New York Dept. of Environmental Conservation,360810124,840360810124
684352,40.816101,-73.902199,2019-06-01T04:00:00Z,PM2.5,15.6,UG/M3,63,2,Bronx - IS52,New York Dept. of Environmental Conservation,360050110,840360050110
684353,40.737500,-73.824400,2019-06-01T04:00:00Z,PM2.5,9.7,UG/M3,52,2,Queens,New York Dept. of Environmental Conservation,360810124,840360810124

In [58]:
aqi_nyc['site_name'].unique()

array(['Fresh Kills', 'Port Richmond', 'Rockland Cty', 'Bklyn - PS 314',
       'Newburgh', 'CCNY', 'Manhattan/IS143', 'Bklyn - PS274',
       'Morrisania', 'Bronx - IS52', 'Maspeth', 'Bronx - IS74', 'Queens',
       'White Plains', 'Holtsville'], dtype=object)

In [59]:
aqi_nyc = aqi_nyc[aqi_nyc['site_name'].isin([
    'Fresh Kills', 'Port Richmond', 'Bklyn - PS 314', 'CCNY', 'Manhattan/IS143', 'Bklyn - PS274',
    'Morrisania', 'Bronx - IS52', 'Maspeth', 'Bronx - IS74', 'Queens',
])]

aqi_nyc

,lat,lon,datetime,param,concentration,unit,aqi,category,site_name,site_agency,aqs_id,aqs_id_full
14,40.580200,-74.199400,2025-05-06T04:00:00Z,PM2.5,6.5,UG/M3,36,1,Fresh Kills,New York Dept. of Environmental Conservation,360850111,840360850111
17,40.633060,-74.137156,2025-05-06T04:00:00Z,PM2.5,0.4,UG/M3,2,1,Port Richmond,New York Dept. of Environmental Conservation,840360850055,840360850055
20,40.641819,-74.018707,2025-05-06T04:00:00Z,PM2.5,10.9,UG/M3,54,2,Bklyn - PS 314,New York Dept. of Environmental Conservation,360470052,840360470052
23,40.819700,-73.948100,2025-05-06T04:00:00Z,PM2.5,4.1,UG/M3,23,1,CCNY,New York Dept. of Environmental Conservation,360610135,840360610135
24,40.849200,-73.931900,2025-05-06T04:00:00Z,PM2.5,4.9,UG/M3,27,1,Manhattan/IS143,New York Dept. of Environmental Conservation,360610115,840360610115
...,...,...,...,...,...,...,...,...,...,...,...,...
684325,40.737500,-73.824400,2019-06-01T02:00:00Z,PM2.5,8.7,UG/M3,48,1,Queens,New York Dept. of Environmental Conservation,360810124,840360810124
684338,40.816101,-73.902199,2019-06-01T03:00:00Z,PM2.5,15.1,UG/M3,62,2,Bronx - IS52,New York Dept. of Environmental Conservation,360050110,840360050110
684339,40.737500,-73.824400,2019-06-01T03:00:00Z,PM2.5,9.3,UG/M3,51,2,Queens,New York Dept. of Environmental Conservation,360810124,840360810124
684352,40.816101,-73.902199,2019-06-01T04:00:00Z,PM2.5,15.6,UG/M3,63,2,Bronx - IS52,New York Dept. of Environmental Conservation,360050110,840360050110
684353,40.737500,-73.824400,2019-06-01T04:00:00Z,PM2.5,9.7,UG/M3,52,2,Queens,New York Dept. of Environmental Conservation,360810124,840360810124

In [60]:
aqi_nyc['unit'].value_counts()

UG/M3    189597
Name: unit, dtype: int64

In [61]:
aqi_nyc['datetime'] = pd.to_datetime(aqi_nyc['datetime'])

aqi_nyc

/var/folders/jd/5wy1jytx2pg8j4jr12tl0k_m0000gq/T/ipykernel_16325/488767915.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aqi_nyc['datetime'] = pd.to_datetime(aqi_nyc['datetime'])

,lat,lon,datetime,param,concentration,unit,aqi,category,site_name,site_agency,aqs_id,aqs_id_full
14,40.580200,-74.199400,2025-05-06 04:00:00+00:00,PM2.5,6.5,UG/M3,36,1,Fresh Kills,New York Dept. of Environmental Conservation,360850111,840360850111
17,40.633060,-74.137156,2025-05-06 04:00:00+00:00,PM2.5,0.4,UG/M3,2,1,Port Richmond,New York Dept. of Environmental Conservation,840360850055,840360850055
20,40.641819,-74.018707,2025-05-06 04:00:00+00:00,PM2.5,10.9,UG/M3,54,2,Bklyn - PS 314,New York Dept. of Environmental Conservation,360470052,840360470052
23,40.819700,-73.948100,2025-05-06 04:00:00+00:00,PM2.5,4.1,UG/M3,23,1,CCNY,New York Dept. of Environmental Conservation,360610135,840360610135
24,40.849200,-73.931900,2025-05-06 04:00:00+00:00,PM2.5,4.9,UG/M3,27,1,Manhattan/IS143,New York Dept. of Environmental Conservation,360610115,840360610115
...,...,...,...,...,...,...,...,...,...,...,...,...
684325,40.737500,-73.824400,2019-06-01 02:00:00+00:00,PM2.5,8.7,UG/M3,48,1,Queens,New York Dept. of Environmental Conservation,360810124,840360810124
684338,40.816101,-73.902199,2019-06-01 03:00:00+00:00,PM2.5,15.1,UG/M3,62,2,Bronx - IS52,New York Dept. of Environmental Conservation,360050110,840360050110
684339,40.737500,-73.824400,2019-06-01 03:00:00+00:00,PM2.5,9.3,UG/M3,51,2,Queens,New York Dept. of Environmental Conservation,360810124,840360810124
684352,40.816101,-73.902199,2019-06-01 04:00:00+00:00,PM2.5,15.6,UG/M3,63,2,Bronx - IS52,New York Dept. of Environmental Conservation,360050110,840360050110
684353,40.737500,-73.824400,2019-06-01 04:00:00+00:00,PM2.5,9.7,UG/M3,52,2,Queens,New York Dept. of Environmental Conservation,360810124,840360810124

In [62]:
# restrict to 2024 onwards
aqi_nyc = aqi_nyc[aqi_nyc['datetime'] >= '2023-05-31']

aqi_nyc

,lat,lon,datetime,param,concentration,unit,aqi,category,site_name,site_agency,aqs_id,aqs_id_full
14,40.580200,-74.199400,2025-05-06 04:00:00+00:00,PM2.5,6.5,UG/M3,36,1,Fresh Kills,New York Dept. of Environmental Conservation,360850111,840360850111
17,40.633060,-74.137156,2025-05-06 04:00:00+00:00,PM2.5,0.4,UG/M3,2,1,Port Richmond,New York Dept. of Environmental Conservation,840360850055,840360850055
20,40.641819,-74.018707,2025-05-06 04:00:00+00:00,PM2.5,10.9,UG/M3,54,2,Bklyn - PS 314,New York Dept. of Environmental Conservation,360470052,840360470052
23,40.819700,-73.948100,2025-05-06 04:00:00+00:00,PM2.5,4.1,UG/M3,23,1,CCNY,New York Dept. of Environmental Conservation,360610135,840360610135
24,40.849200,-73.931900,2025-05-06 04:00:00+00:00,PM2.5,4.9,UG/M3,27,1,Manhattan/IS143,New York Dept. of Environmental Conservation,360610115,840360610115
...,...,...,...,...,...,...,...,...,...,...,...,...
451529,40.836700,-73.921400,2025-05-06 03:00:00+00:00,PM2.5,0.0,UG/M3,0,1,Morrisania,New York Dept. of Environmental Conservation,360050080,840360050080
451530,40.816101,-73.902199,2025-05-06 03:00:00+00:00,PM2.5,3.2,UG/M3,18,1,Bronx - IS52,New York Dept. of Environmental Conservation,360050110,840360050110
451531,40.726900,-73.893300,2025-05-06 03:00:00+00:00,PM2.5,0.5,UG/M3,3,1,Maspeth,New York Dept. of Environmental Conservation,360810120,840360810120
451532,40.814701,-73.886703,2025-05-06 03:00:00+00:00,PM2.5,3.8,UG/M3,21,1,Bronx - IS74,New York Dept. of Environmental Conservation,360050112,840360050112
451533,40.737500,-73.824400,2025-05-06 03:00:00+00:00,PM2.5,3.3,UG/M3,18,1,Queens,New York Dept. of Environmental Conservation,360810124,840360810124

In [63]:
index_cols = ['lat', 'lon', 'param', 'unit', 'site_name']

aqi_daily = aqi_nyc.groupby(index_cols + [aqi_nyc['datetime'].dt.date])['concentration'].agg(['min', 'max']).reset_index()
aqi_daily.rename(columns={'datetime': 'date', 'min': 'daily_low', 'max': 'daily_high'}, inplace=True)

aqi_daily

,lat,lon,param,unit,site_name,date,daily_low,daily_high
0,40.5802,-74.1994,PM2.5,UG/M3,Fresh Kills,2024-01-01,9.4,19.2
1,40.5802,-74.1994,PM2.5,UG/M3,Fresh Kills,2024-01-02,3.7,10.7
2,40.5802,-74.1994,PM2.5,UG/M3,Fresh Kills,2024-01-03,6.1,12.4
3,40.5802,-74.1994,PM2.5,UG/M3,Fresh Kills,2024-01-04,6.1,13.2
4,40.5802,-74.1994,PM2.5,UG/M3,Fresh Kills,2024-01-05,5.7,10.5
...,...,...,...,...,...,...,...,...
5671,40.8492,-73.9319,PM2.5,UG/M3,Manhattan/IS143,2025-05-28,1.6,8.7
5672,40.8492,-73.9319,PM2.5,UG/M3,Manhattan/IS143,2025-05-29,0.0,16.1
5673,40.8492,-73.9319,PM2.5,UG/M3,Manhattan/IS143,2025-05-30,1.1,10.1
5674,40.8492,-73.9319,PM2.5,UG/M3,Manhattan/IS143,2025-05-31,0.0,5.8
5675,40.8492,-73.9319,PM2.5,UG/M3,Manhattan/IS143,2025-06-01,1.4,4.9

In [64]:
# 90 day moving average for daily high
aqi_daily['date'] = pd.to_datetime(aqi_daily['date'])
aqi_daily = aqi_daily.sort_values(by=['site_name', 'date'])
aqi_daily['daily_high_90d_ma'] = aqi_daily.groupby('site_name')['daily_high'].transform(lambda x: x.rolling(window=90, min_periods=1).mean())

In [65]:
# 90 day moving average for daily low
aqi_daily['date'] = pd.to_datetime(aqi_daily['date'])
aqi_daily = aqi_daily.sort_values(by=['site_name', 'date'])
aqi_daily['daily_low_90d_ma'] = aqi_daily.groupby('site_name')['daily_low'].transform(lambda x: x.rolling(window=90, min_periods=1).mean())

In [66]:
# melt
aqi_daily_melted = aqi_daily.melt(id_vars=index_cols + ['date'], value_vars=['daily_low', 'daily_high', 'daily_low_90d_ma', 'daily_high_90d_ma'], var_name='measure', value_name='concentration')

aqi_daily_melted['date'] = pd.to_datetime(aqi_daily_melted['date'])

In [ ]:
import numpy as np

# replace -999.0 with NaN
aqi_daily_melted['concentration'] = aqi_daily_melted['concentration'].replace(-999.0, np.nan)

RecursionError: maximum recursion depth exceeded

In [ ]:
aqi_daily_melted.to_csv('data/processed/air_quality_nyc_daily.csv', index=False)