In [99]:
import pandas as pd
import numpy as np
import pyreadr as pr

In [96]:
air_quality_url = "https://raw.githubusercontent.com/timothyfraser/nyc_congestion_rep/refs/heads/main/data/air_quality.csv"

In [106]:
sites_filepath = "data/raw/sites.rds"

In [97]:
aqi = pd.read_csv(air_quality_url)

aqi.head()

    aqs_id_full              datetime pollutant  value   unit
0  840421010055  2025-05-06T04:00:00Z     PM2.5    5.6  UG/M3
1  840421010057  2025-05-06T04:00:00Z     PM2.5    5.1  UG/M3
2  840340070010  2025-05-06T04:00:00Z     PM2.5    5.0  UG/M3
3  840421010048  2025-05-06T04:00:00Z     PM2.5    4.1  UG/M3
4  840340410007  2025-05-06T04:00:00Z     PM2.5    1.3  UG/M3

In [98]:
aqi.to_csv('data/raw/air_quality_nyc.csv', index=False)

In [108]:
sites_filepath = "data/raw/air_quality_nyc_sites.csv"

In [124]:
sites = pd.read_csv(sites_filepath)
sites = sites[~sites['aqs_id_full'].isna()]

sites

,aqs_id,aqs_id_full,site_name,geometry,dist,nyc_id,name,within
0,999999991,840999999991,Manhattan Bridge,"c(-73.997004, 40.71651)",0.706539,36061NY08454,New York,1
1,999999992,840999999992,Hunts Point,"c(-73.885659, 40.819092)",9.063318,36005NY11790,Bronx,0
2,999999993,840999999993,Glendale,"c(-73.873400059669, 40.7071127856604)",8.519605,36081NY08198,Queens,0
3,999999994,840999999994,Queens College,"c(-73.821556, 40.737107)",11.802003,36081NY09285,Queens,0
4,999999995,840999999995,Broadway/35th St,"c(-73.98783, 40.75069)",1.515596,36061NY09734,New York,1
5,999999996,840999999996,FDR,"c(-73.974651, 40.722288)",0.018061,36061NY08653,New York,1
6,999999997,840999999997,Mott Haven,"c(-73.922487, 40.806486)",6.079127,36005NY11534,Bronx,0
7,999999998,840999999998,Cross Bronx Expy,"c(-73.906143, 40.845167)",10.497637,36005NY12387,Bronx,0
8,999999999,840999999999,Van Wyck,"c(-73.80908, 40.690155)",14.209708,36081NY07615,Queens,0
9,999999910,840999999910,Queens College,"c(-73.821556, 40.737107)",11.802003,36081NY09285B,Queens,0
10,999999911,840999999911,BQE,"c(-73.960824, 40.702798)",1.617640,36047NY07974,Kings,0
11,999999912,840999999912,Williamsburg,"c(-73.95938, 40.710614)",1.367977,36047NY08274,Kings,0
12,999999913,840999999913,Queensboro Bridge,"c(-73.963886, 40.761234)",0.012354,36061NY10130,New York,1
13,999999914,840999999914,Williamsburg Bridge,"c(-73.986059, 40.718073)",0.801937,36061NY08552,New York,1
14,999999915,840999999915,Hamilton Bridge,"c(-73.933023, 40.846544)",9.537356,36061NY12380,New York,0
15,999999916,840999999916,Midtown-DOT,"c(-73.990415, 40.755082)",1.132279,36061NY09929,New York,1
16,999999917,840999999917,Port Richmond,"c(-74.145883, 40.627925)",13.639928,36085NY04805,Richmond,0
17,999999918,840999999918,SI Expwy,"c(-74.151182, 40.609209)",15.337497,36085NY03820,Richmond,0

In [ ]:
sites[['lon', 'lat']] = sites['geometry'].str.extract(r'c\(([-\d.]+),\s*([-\d.]+)\)')
sites[['lon', 'lat']] = sites[['lon', 'lat']].astype(float)

sites

4       c(-73.98783, 40.75069)
12    c(-73.963886, 40.761234)
0      c(-73.997004, 40.71651)
13    c(-73.986059, 40.718073)
7     c(-73.906143, 40.845167)
Name: geometry, dtype: object

In [116]:
sites['geometry'].sample(5)

999999998            40.845167)
999999993     40.7071127856604)
999999994            40.737107)
999999917            40.627925)
999999918            40.609209)
Name: geometry, dtype: object

In [77]:
aqi['site_agency'].value_counts()

New York Dept. of Environmental Conservation                271126
New Jersey Dept. of Environmental Protection                266233
Connecticut Dept. of Energy and Environmental Protection     98258
Philadelphia Air Management Services                         48741
Name: site_agency, dtype: int64

In [78]:
aqi_nyc = aqi[aqi['site_agency'] == 'New York Dept. of Environmental Conservation']

aqi_nyc

,lat,lon,datetime,param,concentration,unit,aqi,category,site_name,site_agency,aqs_id,aqs_id_full
14,40.580200,-74.199400,2025-05-06T04:00:00Z,PM2.5,6.5,UG/M3,36,1,Fresh Kills,New York Dept. of Environmental Conservation,360850111,840360850111
17,40.633060,-74.137156,2025-05-06T04:00:00Z,PM2.5,0.4,UG/M3,2,1,Port Richmond,New York Dept. of Environmental Conservation,840360850055,840360850055
19,41.182079,-74.028191,2025-05-06T04:00:00Z,PM2.5,0.0,UG/M3,0,1,Rockland Cty,New York Dept. of Environmental Conservation,360870005,840360870005
20,40.641819,-74.018707,2025-05-06T04:00:00Z,PM2.5,10.9,UG/M3,54,2,Bklyn - PS 314,New York Dept. of Environmental Conservation,360470052,840360470052
21,41.499400,-74.009700,2025-05-06T04:00:00Z,PM2.5,0.0,UG/M3,0,1,Newburgh,New York Dept. of Environmental Conservation,360710002,840360710002
...,...,...,...,...,...,...,...,...,...,...,...,...
684325,40.737500,-73.824400,2019-06-01T02:00:00Z,PM2.5,8.7,UG/M3,48,1,Queens,New York Dept. of Environmental Conservation,360810124,840360810124
684338,40.816101,-73.902199,2019-06-01T03:00:00Z,PM2.5,15.1,UG/M3,62,2,Bronx - IS52,New York Dept. of Environmental Conservation,360050110,840360050110
684339,40.737500,-73.824400,2019-06-01T03:00:00Z,PM2.5,9.3,UG/M3,51,2,Queens,New York Dept. of Environmental Conservation,360810124,840360810124
684352,40.816101,-73.902199,2019-06-01T04:00:00Z,PM2.5,15.6,UG/M3,63,2,Bronx - IS52,New York Dept. of Environmental Conservation,360050110,840360050110
684353,40.737500,-73.824400,2019-06-01T04:00:00Z,PM2.5,9.7,UG/M3,52,2,Queens,New York Dept. of Environmental Conservation,360810124,840360810124

In [79]:
aqi_nyc['site_name'].unique()

array(['Fresh Kills', 'Port Richmond', 'Rockland Cty', 'Bklyn - PS 314',
       'Newburgh', 'CCNY', 'Manhattan/IS143', 'Bklyn - PS274',
       'Morrisania', 'Bronx - IS52', 'Maspeth', 'Bronx - IS74', 'Queens',
       'White Plains', 'Holtsville'], dtype=object)

In [80]:
aqi_nyc = aqi_nyc[aqi_nyc['site_name'].isin([
    'Fresh Kills', 'Port Richmond', 'Bklyn - PS 314', 'CCNY', 'Manhattan/IS143', 'Bklyn - PS274',
    'Morrisania', 'Bronx - IS52', 'Maspeth', 'Bronx - IS74', 'Queens',
])]

aqi_nyc

,lat,lon,datetime,param,concentration,unit,aqi,category,site_name,site_agency,aqs_id,aqs_id_full
14,40.580200,-74.199400,2025-05-06T04:00:00Z,PM2.5,6.5,UG/M3,36,1,Fresh Kills,New York Dept. of Environmental Conservation,360850111,840360850111
17,40.633060,-74.137156,2025-05-06T04:00:00Z,PM2.5,0.4,UG/M3,2,1,Port Richmond,New York Dept. of Environmental Conservation,840360850055,840360850055
20,40.641819,-74.018707,2025-05-06T04:00:00Z,PM2.5,10.9,UG/M3,54,2,Bklyn - PS 314,New York Dept. of Environmental Conservation,360470052,840360470052
23,40.819700,-73.948100,2025-05-06T04:00:00Z,PM2.5,4.1,UG/M3,23,1,CCNY,New York Dept. of Environmental Conservation,360610135,840360610135
24,40.849200,-73.931900,2025-05-06T04:00:00Z,PM2.5,4.9,UG/M3,27,1,Manhattan/IS143,New York Dept. of Environmental Conservation,360610115,840360610115
...,...,...,...,...,...,...,...,...,...,...,...,...
684325,40.737500,-73.824400,2019-06-01T02:00:00Z,PM2.5,8.7,UG/M3,48,1,Queens,New York Dept. of Environmental Conservation,360810124,840360810124
684338,40.816101,-73.902199,2019-06-01T03:00:00Z,PM2.5,15.1,UG/M3,62,2,Bronx - IS52,New York Dept. of Environmental Conservation,360050110,840360050110
684339,40.737500,-73.824400,2019-06-01T03:00:00Z,PM2.5,9.3,UG/M3,51,2,Queens,New York Dept. of Environmental Conservation,360810124,840360810124
684352,40.816101,-73.902199,2019-06-01T04:00:00Z,PM2.5,15.6,UG/M3,63,2,Bronx - IS52,New York Dept. of Environmental Conservation,360050110,840360050110
684353,40.737500,-73.824400,2019-06-01T04:00:00Z,PM2.5,9.7,UG/M3,52,2,Queens,New York Dept. of Environmental Conservation,360810124,840360810124

In [81]:
aqi_nyc['unit'].value_counts()

UG/M3    189597
Name: unit, dtype: int64

In [82]:
aqi_nyc['datetime'] = pd.to_datetime(aqi_nyc['datetime'])

aqi_nyc

/var/folders/jd/5wy1jytx2pg8j4jr12tl0k_m0000gq/T/ipykernel_16325/488767915.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aqi_nyc['datetime'] = pd.to_datetime(aqi_nyc['datetime'])

,lat,lon,datetime,param,concentration,unit,aqi,category,site_name,site_agency,aqs_id,aqs_id_full
14,40.580200,-74.199400,2025-05-06 04:00:00+00:00,PM2.5,6.5,UG/M3,36,1,Fresh Kills,New York Dept. of Environmental Conservation,360850111,840360850111
17,40.633060,-74.137156,2025-05-06 04:00:00+00:00,PM2.5,0.4,UG/M3,2,1,Port Richmond,New York Dept. of Environmental Conservation,840360850055,840360850055
20,40.641819,-74.018707,2025-05-06 04:00:00+00:00,PM2.5,10.9,UG/M3,54,2,Bklyn - PS 314,New York Dept. of Environmental Conservation,360470052,840360470052
23,40.819700,-73.948100,2025-05-06 04:00:00+00:00,PM2.5,4.1,UG/M3,23,1,CCNY,New York Dept. of Environmental Conservation,360610135,840360610135
24,40.849200,-73.931900,2025-05-06 04:00:00+00:00,PM2.5,4.9,UG/M3,27,1,Manhattan/IS143,New York Dept. of Environmental Conservation,360610115,840360610115
...,...,...,...,...,...,...,...,...,...,...,...,...
684325,40.737500,-73.824400,2019-06-01 02:00:00+00:00,PM2.5,8.7,UG/M3,48,1,Queens,New York Dept. of Environmental Conservation,360810124,840360810124
684338,40.816101,-73.902199,2019-06-01 03:00:00+00:00,PM2.5,15.1,UG/M3,62,2,Bronx - IS52,New York Dept. of Environmental Conservation,360050110,840360050110
684339,40.737500,-73.824400,2019-06-01 03:00:00+00:00,PM2.5,9.3,UG/M3,51,2,Queens,New York Dept. of Environmental Conservation,360810124,840360810124
684352,40.816101,-73.902199,2019-06-01 04:00:00+00:00,PM2.5,15.6,UG/M3,63,2,Bronx - IS52,New York Dept. of Environmental Conservation,360050110,840360050110
684353,40.737500,-73.824400,2019-06-01 04:00:00+00:00,PM2.5,9.7,UG/M3,52,2,Queens,New York Dept. of Environmental Conservation,360810124,840360810124

In [83]:
# restrict to 2024 onwards
aqi_nyc = aqi_nyc[aqi_nyc['datetime'] >= '2023-05-31']

aqi_nyc

,lat,lon,datetime,param,concentration,unit,aqi,category,site_name,site_agency,aqs_id,aqs_id_full
14,40.580200,-74.199400,2025-05-06 04:00:00+00:00,PM2.5,6.5,UG/M3,36,1,Fresh Kills,New York Dept. of Environmental Conservation,360850111,840360850111
17,40.633060,-74.137156,2025-05-06 04:00:00+00:00,PM2.5,0.4,UG/M3,2,1,Port Richmond,New York Dept. of Environmental Conservation,840360850055,840360850055
20,40.641819,-74.018707,2025-05-06 04:00:00+00:00,PM2.5,10.9,UG/M3,54,2,Bklyn - PS 314,New York Dept. of Environmental Conservation,360470052,840360470052
23,40.819700,-73.948100,2025-05-06 04:00:00+00:00,PM2.5,4.1,UG/M3,23,1,CCNY,New York Dept. of Environmental Conservation,360610135,840360610135
24,40.849200,-73.931900,2025-05-06 04:00:00+00:00,PM2.5,4.9,UG/M3,27,1,Manhattan/IS143,New York Dept. of Environmental Conservation,360610115,840360610115
...,...,...,...,...,...,...,...,...,...,...,...,...
451529,40.836700,-73.921400,2025-05-06 03:00:00+00:00,PM2.5,0.0,UG/M3,0,1,Morrisania,New York Dept. of Environmental Conservation,360050080,840360050080
451530,40.816101,-73.902199,2025-05-06 03:00:00+00:00,PM2.5,3.2,UG/M3,18,1,Bronx - IS52,New York Dept. of Environmental Conservation,360050110,840360050110
451531,40.726900,-73.893300,2025-05-06 03:00:00+00:00,PM2.5,0.5,UG/M3,3,1,Maspeth,New York Dept. of Environmental Conservation,360810120,840360810120
451532,40.814701,-73.886703,2025-05-06 03:00:00+00:00,PM2.5,3.8,UG/M3,21,1,Bronx - IS74,New York Dept. of Environmental Conservation,360050112,840360050112
451533,40.737500,-73.824400,2025-05-06 03:00:00+00:00,PM2.5,3.3,UG/M3,18,1,Queens,New York Dept. of Environmental Conservation,360810124,840360810124

In [84]:
index_cols = ['lat', 'lon', 'param', 'unit', 'site_name']

aqi_daily = aqi_nyc.groupby(index_cols + [aqi_nyc['datetime'].dt.date])['concentration'].agg(['min', 'max']).reset_index()
aqi_daily.rename(columns={'datetime': 'date', 'min': 'daily_low', 'max': 'daily_high'}, inplace=True)

aqi_daily

,lat,lon,param,unit,site_name,date,daily_low,daily_high
0,40.5802,-74.1994,PM2.5,UG/M3,Fresh Kills,2024-01-01,9.4,19.2
1,40.5802,-74.1994,PM2.5,UG/M3,Fresh Kills,2024-01-02,3.7,10.7
2,40.5802,-74.1994,PM2.5,UG/M3,Fresh Kills,2024-01-03,6.1,12.4
3,40.5802,-74.1994,PM2.5,UG/M3,Fresh Kills,2024-01-04,6.1,13.2
4,40.5802,-74.1994,PM2.5,UG/M3,Fresh Kills,2024-01-05,5.7,10.5
...,...,...,...,...,...,...,...,...
5671,40.8492,-73.9319,PM2.5,UG/M3,Manhattan/IS143,2025-05-28,1.6,8.7
5672,40.8492,-73.9319,PM2.5,UG/M3,Manhattan/IS143,2025-05-29,0.0,16.1
5673,40.8492,-73.9319,PM2.5,UG/M3,Manhattan/IS143,2025-05-30,1.1,10.1
5674,40.8492,-73.9319,PM2.5,UG/M3,Manhattan/IS143,2025-05-31,0.0,5.8
5675,40.8492,-73.9319,PM2.5,UG/M3,Manhattan/IS143,2025-06-01,1.4,4.9

In [85]:
aqi_daily['daily_high'] = aqi_daily['daily_high'].replace(-999.0, np.nan)
aqi_daily['daily_low'] = aqi_daily['daily_low'].replace(-999.0, np.nan)

In [86]:
# 90 day moving average for daily high
aqi_daily['date'] = pd.to_datetime(aqi_daily['date'])
aqi_daily = aqi_daily.sort_values(by=['site_name', 'date'])
aqi_daily['daily_high_90d_ma'] = aqi_daily.groupby('site_name')['daily_high'].transform(lambda x: x.rolling(window=90, min_periods=1).mean())

In [87]:
# 90 day moving average for daily low
aqi_daily['date'] = pd.to_datetime(aqi_daily['date'])
aqi_daily = aqi_daily.sort_values(by=['site_name', 'date'])
aqi_daily['daily_low_90d_ma'] = aqi_daily.groupby('site_name')['daily_low'].transform(lambda x: x.rolling(window=90, min_periods=1).mean())

In [88]:
# melt
aqi_daily_melted = aqi_daily.melt(id_vars=index_cols + ['date'], value_vars=['daily_low', 'daily_high', 'daily_low_90d_ma', 'daily_high_90d_ma'], var_name='measure', value_name='concentration')

aqi_daily_melted['date'] = pd.to_datetime(aqi_daily_melted['date'])

In [89]:
aqi_daily_melted.to_csv('data/processed/air_quality_nyc_daily.csv', index=False)

In [91]:
aqi_sites = aqi_daily_melted.drop_duplicates(subset=['site_name', 'lat', 'lon'])[['site_name', 'lat', 'lon']]

In [93]:
aqi_sites.to_csv('data/processed/air_quality_nyc_sites.csv', index=False)

In [94]:
aqi_sites

            site_name        lat        lon
0      Bklyn - PS 314  40.641819 -74.018707
515     Bklyn - PS274  40.694401 -73.928596
1029     Bronx - IS52  40.816101 -73.902199
1538     Bronx - IS74  40.814701 -73.886703
2056             CCNY  40.819700 -73.948100
2573      Fresh Kills  40.580200 -74.199400
3091  Manhattan/IS143  40.849200 -73.931900
3609          Maspeth  40.726900 -73.893300
4125       Morrisania  40.836700 -73.921400
4643    Port Richmond  40.633060 -74.137156
5159           Queens  40.737500 -73.824400