In [130]:
import pandas as pd
import numpy as np
import pyreadr as pr

In [131]:
air_quality_url = "https://raw.githubusercontent.com/timothyfraser/nyc_congestion_rep/refs/heads/main/data/air_quality.csv"

In [132]:
sites_filepath = "data/raw/sites.rds"

In [133]:
aqi = pd.read_csv(air_quality_url)

aqi.head()

    aqs_id_full              datetime pollutant  value   unit
0  840421010055  2025-05-06T04:00:00Z     PM2.5    5.6  UG/M3
1  840421010057  2025-05-06T04:00:00Z     PM2.5    5.1  UG/M3
2  840340070010  2025-05-06T04:00:00Z     PM2.5    5.0  UG/M3
3  840421010048  2025-05-06T04:00:00Z     PM2.5    4.1  UG/M3
4  840340410007  2025-05-06T04:00:00Z     PM2.5    1.3  UG/M3

In [134]:
aqi.to_csv('data/raw/air_quality_nyc.csv', index=False)

In [135]:
sites_filepath = "data/raw/air_quality_nyc_sites.csv"

In [136]:
sites = pd.read_csv(sites_filepath)
sites = sites[~sites['aqs_id_full'].isna()]

sites

,aqs_id,aqs_id_full,site_name,geometry,dist,nyc_id,name,within
0,999999991,840999999991,Manhattan Bridge,"c(-73.997004, 40.71651)",0.706539,36061NY08454,New York,1
1,999999992,840999999992,Hunts Point,"c(-73.885659, 40.819092)",9.063318,36005NY11790,Bronx,0
2,999999993,840999999993,Glendale,"c(-73.873400059669, 40.7071127856604)",8.519605,36081NY08198,Queens,0
3,999999994,840999999994,Queens College,"c(-73.821556, 40.737107)",11.802003,36081NY09285,Queens,0
4,999999995,840999999995,Broadway/35th St,"c(-73.98783, 40.75069)",1.515596,36061NY09734,New York,1
5,999999996,840999999996,FDR,"c(-73.974651, 40.722288)",0.018061,36061NY08653,New York,1
6,999999997,840999999997,Mott Haven,"c(-73.922487, 40.806486)",6.079127,36005NY11534,Bronx,0
7,999999998,840999999998,Cross Bronx Expy,"c(-73.906143, 40.845167)",10.497637,36005NY12387,Bronx,0
8,999999999,840999999999,Van Wyck,"c(-73.80908, 40.690155)",14.209708,36081NY07615,Queens,0
9,999999910,840999999910,Queens College,"c(-73.821556, 40.737107)",11.802003,36081NY09285B,Queens,0
10,999999911,840999999911,BQE,"c(-73.960824, 40.702798)",1.617640,36047NY07974,Kings,0
11,999999912,840999999912,Williamsburg,"c(-73.95938, 40.710614)",1.367977,36047NY08274,Kings,0
12,999999913,840999999913,Queensboro Bridge,"c(-73.963886, 40.761234)",0.012354,36061NY10130,New York,1
13,999999914,840999999914,Williamsburg Bridge,"c(-73.986059, 40.718073)",0.801937,36061NY08552,New York,1
14,999999915,840999999915,Hamilton Bridge,"c(-73.933023, 40.846544)",9.537356,36061NY12380,New York,0
15,999999916,840999999916,Midtown-DOT,"c(-73.990415, 40.755082)",1.132279,36061NY09929,New York,1
16,999999917,840999999917,Port Richmond,"c(-74.145883, 40.627925)",13.639928,36085NY04805,Richmond,0
17,999999918,840999999918,SI Expwy,"c(-74.151182, 40.609209)",15.337497,36085NY03820,Richmond,0

In [137]:
sites[['lon', 'lat']] = sites['geometry'].str.extract(r'c\(([-\d.]+),\s*([-\d.]+)\)')
sites[['lon', 'lat']] = sites[['lon', 'lat']].astype(float)

sites

,aqs_id,aqs_id_full,site_name,geometry,dist,nyc_id,name,within,lon,lat
0,999999991,840999999991,Manhattan Bridge,"c(-73.997004, 40.71651)",0.706539,36061NY08454,New York,1,-73.997004,40.716510
1,999999992,840999999992,Hunts Point,"c(-73.885659, 40.819092)",9.063318,36005NY11790,Bronx,0,-73.885659,40.819092
2,999999993,840999999993,Glendale,"c(-73.873400059669, 40.7071127856604)",8.519605,36081NY08198,Queens,0,-73.873400,40.707113
3,999999994,840999999994,Queens College,"c(-73.821556, 40.737107)",11.802003,36081NY09285,Queens,0,-73.821556,40.737107
4,999999995,840999999995,Broadway/35th St,"c(-73.98783, 40.75069)",1.515596,36061NY09734,New York,1,-73.987830,40.750690
5,999999996,840999999996,FDR,"c(-73.974651, 40.722288)",0.018061,36061NY08653,New York,1,-73.974651,40.722288
6,999999997,840999999997,Mott Haven,"c(-73.922487, 40.806486)",6.079127,36005NY11534,Bronx,0,-73.922487,40.806486
7,999999998,840999999998,Cross Bronx Expy,"c(-73.906143, 40.845167)",10.497637,36005NY12387,Bronx,0,-73.906143,40.845167
8,999999999,840999999999,Van Wyck,"c(-73.80908, 40.690155)",14.209708,36081NY07615,Queens,0,-73.809080,40.690155
9,999999910,840999999910,Queens College,"c(-73.821556, 40.737107)",11.802003,36081NY09285B,Queens,0,-73.821556,40.737107
10,999999911,840999999911,BQE,"c(-73.960824, 40.702798)",1.617640,36047NY07974,Kings,0,-73.960824,40.702798
11,999999912,840999999912,Williamsburg,"c(-73.95938, 40.710614)",1.367977,36047NY08274,Kings,0,-73.959380,40.710614
12,999999913,840999999913,Queensboro Bridge,"c(-73.963886, 40.761234)",0.012354,36061NY10130,New York,1,-73.963886,40.761234
13,999999914,840999999914,Williamsburg Bridge,"c(-73.986059, 40.718073)",0.801937,36061NY08552,New York,1,-73.986059,40.718073
14,999999915,840999999915,Hamilton Bridge,"c(-73.933023, 40.846544)",9.537356,36061NY12380,New York,0,-73.933023,40.846544
15,999999916,840999999916,Midtown-DOT,"c(-73.990415, 40.755082)",1.132279,36061NY09929,New York,1,-73.990415,40.755082
16,999999917,840999999917,Port Richmond,"c(-74.145883, 40.627925)",13.639928,36085NY04805,Richmond,0,-74.145883,40.627925
17,999999918,840999999918,SI Expwy,"c(-74.151182, 40.609209)",15.337497,36085NY03820,Richmond,0,-74.151182,40.609209

In [138]:
sites.to_csv('data/processed/air_quality_nyc_sites.csv', index=False)

In [139]:
# merge aqi with site locations
aqi = aqi.merge(sites[['aqs_id_full', 'site_name','lon', 'lat']], on='aqs_id_full', how='left')

aqi

,aqs_id_full,datetime,pollutant,value,unit,site_name,lon,lat
0,840421010055,2025-05-06T04:00:00Z,PM2.5,5.60,UG/M3,NaN,NaN,NaN
1,840421010057,2025-05-06T04:00:00Z,PM2.5,5.10,UG/M3,NaN,NaN,NaN
2,840340070010,2025-05-06T04:00:00Z,PM2.5,5.00,UG/M3,NaN,NaN,NaN
3,840421010048,2025-05-06T04:00:00Z,PM2.5,4.10,UG/M3,NaN,NaN,NaN
4,840340410007,2025-05-06T04:00:00Z,PM2.5,1.30,UG/M3,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
1522018,840999999996,2025-05-31T23:00:00Z,PM25,5.40,UG/M3,FDR,-73.974651,40.722288
1522019,840999999999,2025-05-31T23:00:00Z,PM25,4.39,UG/M3,Van Wyck,-73.809080,40.690155
1522020,840999999918,2025-05-31T23:00:00Z,PM25,5.35,UG/M3,SI Expwy,-74.151182,40.609209
1522021,840999999911,2025-05-31T23:00:00Z,PM25,4.56,UG/M3,BQE,-73.960824,40.702798
1522022,840999999915,2025-05-31T23:00:00Z,PM25,6.23,UG/M3,Hamilton Bridge,-73.933023,40.846544

In [141]:
aqi = aqi[aqi['site_name'].notna()]

aqi = aqi.reset_index(drop=True)

In [144]:
aqi

,aqs_id_full,datetime,pollutant,value,unit,site_name,lon,lat
0,840999999994,2019-05-07T17:00:00Z,PM25,5.17,UG/M3,Queens College,-73.821556,40.737107
1,840999999994,2019-05-07T18:00:00Z,PM25,5.10,UG/M3,Queens College,-73.821556,40.737107
2,840999999994,2019-05-07T19:00:00Z,PM25,5.40,UG/M3,Queens College,-73.821556,40.737107
3,840999999994,2019-05-07T20:00:00Z,PM25,5.68,UG/M3,Queens College,-73.821556,40.737107
4,840999999994,2019-05-07T21:00:00Z,PM25,5.97,UG/M3,Queens College,-73.821556,40.737107
...,...,...,...,...,...,...,...,...
153302,840999999996,2025-05-31T23:00:00Z,PM25,5.40,UG/M3,FDR,-73.974651,40.722288
153303,840999999999,2025-05-31T23:00:00Z,PM25,4.39,UG/M3,Van Wyck,-73.809080,40.690155
153304,840999999918,2025-05-31T23:00:00Z,PM25,5.35,UG/M3,SI Expwy,-74.151182,40.609209
153305,840999999911,2025-05-31T23:00:00Z,PM25,4.56,UG/M3,BQE,-73.960824,40.702798
153306,840999999915,2025-05-31T23:00:00Z,PM25,6.23,UG/M3,Hamilton Bridge,-73.933023,40.846544

In [146]:
# restrict to 2023 onwards
aqi['datetime'] = pd.to_datetime(aqi['datetime'])
aqi = aqi[aqi['datetime'] >= '2023-01-01']

In [147]:
aqi['value'].describe()

count    131863.000000
mean          7.550384
std           5.081887
min           2.190000
25%           4.360000
50%           6.100000
75%           9.270000
max         265.210000
Name: value, dtype: float64

In [151]:
aqi

,aqs_id_full,datetime,pollutant,value,unit,site_name,lon,lat
21444,840999999913,2024-01-01 00:00:00+00:00,PM25,7.39,UG/M3,Queensboro Bridge,-73.963886,40.761234
21445,840999999916,2024-01-01 00:00:00+00:00,PM25,18.91,UG/M3,Midtown-DOT,-73.990415,40.755082
21446,840999999995,2024-01-01 00:00:00+00:00,PM25,9.91,UG/M3,Broadway/35th St,-73.987830,40.750690
21447,840999999998,2024-01-01 00:00:00+00:00,PM25,8.57,UG/M3,Cross Bronx Expy,-73.906143,40.845167
21448,840999999994,2024-01-01 00:00:00+00:00,PM25,6.29,UG/M3,Queens College,-73.821556,40.737107
...,...,...,...,...,...,...,...,...
153302,840999999996,2025-05-31 23:00:00+00:00,PM25,5.40,UG/M3,FDR,-73.974651,40.722288
153303,840999999999,2025-05-31 23:00:00+00:00,PM25,4.39,UG/M3,Van Wyck,-73.809080,40.690155
153304,840999999918,2025-05-31 23:00:00+00:00,PM25,5.35,UG/M3,SI Expwy,-74.151182,40.609209
153305,840999999911,2025-05-31 23:00:00+00:00,PM25,4.56,UG/M3,BQE,-73.960824,40.702798
153306,840999999915,2025-05-31 23:00:00+00:00,PM25,6.23,UG/M3,Hamilton Bridge,-73.933023,40.846544

In [152]:
index_cols = ['aqs_id_full', 'pollutant', 'unit', 'site_name', 'lon', 'lat']

aqi_daily = aqi.groupby(index_cols + [aqi['datetime'].dt.date])['value'].agg(['min', 'max']).reset_index()
aqi_daily.rename(columns={'datetime': 'date', 'min': 'daily_low', 'max': 'daily_high'}, inplace=True)
aqi_daily['date'] = pd.to_datetime(aqi_daily['date'])

aqi_daily

,aqs_id_full,pollutant,unit,site_name,lon,lat,date,daily_low,daily_high
0,840999999911,PM25,UG/M3,BQE,-73.960824,40.702798,2024-07-03,8.78,10.64
1,840999999911,PM25,UG/M3,BQE,-73.960824,40.702798,2024-07-04,10.57,16.16
2,840999999911,PM25,UG/M3,BQE,-73.960824,40.702798,2024-07-05,17.83,203.41
3,840999999911,PM25,UG/M3,BQE,-73.960824,40.702798,2024-07-06,17.67,34.69
4,840999999911,PM25,UG/M3,BQE,-73.960824,40.702798,2024-07-07,9.78,34.68
...,...,...,...,...,...,...,...,...,...
5530,840999999999,PM25,UG/M3,Van Wyck,-73.809080,40.690155,2025-05-27,4.01,9.25
5531,840999999999,PM25,UG/M3,Van Wyck,-73.809080,40.690155,2025-05-28,2.73,6.67
5532,840999999999,PM25,UG/M3,Van Wyck,-73.809080,40.690155,2025-05-29,2.19,9.16
5533,840999999999,PM25,UG/M3,Van Wyck,-73.809080,40.690155,2025-05-30,3.57,13.28
5534,840999999999,PM25,UG/M3,Van Wyck,-73.809080,40.690155,2025-05-31,2.97,9.61

In [153]:
# 90 day moving average for daily high
aqi_daily['date'] = pd.to_datetime(aqi_daily['date'])
aqi_daily = aqi_daily.sort_values(by=['site_name', 'date'])
aqi_daily['daily_high_90d_ma'] = aqi_daily.groupby('site_name')['daily_high'].transform(lambda x: x.rolling(window=90, min_periods=1).mean())

# 90 day moving average for daily low
aqi_daily['date'] = pd.to_datetime(aqi_daily['date'])
aqi_daily = aqi_daily.sort_values(by=['site_name', 'date'])
aqi_daily['daily_low_90d_ma'] = aqi_daily.groupby('site_name')['daily_low'].transform(lambda x: x.rolling(window=90, min_periods=1).mean())

aqi_daily

,aqs_id_full,pollutant,unit,site_name,lon,lat,date,daily_low,daily_high,daily_high_90d_ma,daily_low_90d_ma
0,840999999911,PM25,UG/M3,BQE,-73.960824,40.702798,2024-07-03,8.78,10.64,10.640000,8.780000
1,840999999911,PM25,UG/M3,BQE,-73.960824,40.702798,2024-07-04,10.57,16.16,13.400000,9.675000
2,840999999911,PM25,UG/M3,BQE,-73.960824,40.702798,2024-07-05,17.83,203.41,76.736667,12.393333
3,840999999911,PM25,UG/M3,BQE,-73.960824,40.702798,2024-07-06,17.67,34.69,66.225000,13.712500
4,840999999911,PM25,UG/M3,BQE,-73.960824,40.702798,2024-07-07,9.78,34.68,59.916000,12.926000
...,...,...,...,...,...,...,...,...,...,...,...
1197,840999999914,PM25,UG/M3,Williamsburg Bridge,-73.986059,40.718073,2025-05-27,2.23,8.88,9.983000,3.972778
1198,840999999914,PM25,UG/M3,Williamsburg Bridge,-73.986059,40.718073,2025-05-28,3.57,7.43,9.847778,3.943667
1199,840999999914,PM25,UG/M3,Williamsburg Bridge,-73.986059,40.718073,2025-05-29,3.84,10.28,9.807667,3.946111
1200,840999999914,PM25,UG/M3,Williamsburg Bridge,-73.986059,40.718073,2025-05-30,4.79,14.95,9.904000,3.959111
1201,840999999914,PM25,UG/M3,Williamsburg Bridge,-73.986059,40.718073,2025-05-31,3.01,11.30,9.975222,3.952444

In [ ]:
# melt
aqi_daily_melted = aqi_daily.melt(id_vars=index_cols + ['date'], value_vars=['daily_low', 'daily_high', 'daily_low_90d_ma', 'daily_high_90d_ma'], var_name='measure', value_name='concentration')

aqi_daily_melted['date'] = pd.to_datetime(aqi_daily_melted['date'])

In [ ]:
aqi_daily_melted = aqi_daily_melted[aqi_daily_melted['site_name'].isin(
    ['Queens College','Midtown-DOT', 'BQE', 'Hamilton Bridge', 'Mott Haven', 'SI Expwy', 'Broadway/35th St']
)]

In [157]:
aqi_daily_melted['site_name'] = aqi_daily_melted['site_name'].map({
    'Queens College': 'Queens College (Queens)',
    'Midtown-DOT': 'Midtown-DOT (Manhattan)',
    'BQE': 'BQE (Brooklyn)',
    'Hamilton Bridge': 'Hamilton Bridge (Bronx)',
    'Mott Haven': 'Mott Haven (Bronx)',
    'SI Expwy': 'SI Expwy (Staten Island)',
    'Broadway/35th St': 'Broadway/35th St (Manhattan)'
})

In [160]:
# order sites by borough
borough_order = {
    'Midtown-DOT (Manhattan)': 1,
    'Broadway/35th St (Manhattan)': 2,
    'BQE (Brooklyn)': 3,
    'Queens College (Queens)': 4,
    'Hamilton Bridge (Bronx)': 5,
    'Mott Haven (Bronx)': 6,
    'SI Expwy (Staten Island)': 7
}

aqi_daily_melted['site_order'] = aqi_daily_melted['site_name'].map(borough_order)
aqi_daily_melted = aqi_daily_melted.sort_values(by=['site_order', 'date'])
aqi_daily_melted = aqi_daily_melted.drop(columns=['site_order'])

In [161]:
aqi_daily_melted.to_csv('data/processed/air_quality_nyc_daily.csv', index=False)