In [12]:
import pandas as pd

# I. Get Zillow Data

### i. Counties

In [2]:
# checking if the county zillow link still works
county_wide_url = "https://files.zillowstatic.com/research/public_csvs/zori/County_zori_uc_sfrcondomfr_sm_month.csv?t=1734717130"

In [3]:
zori_county_wide = pd.read_csv(county_wide_url)

zori_county_wide.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,2015-01-31,...,2025-01-31,2025-02-28,2025-03-31,2025-04-30,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31
0,3101,0,Los Angeles County,county,CA,CA,"Los Angeles-Long Beach-Anaheim, CA",6,37,1710.142975,...,2779.603168,2802.865470,2826.578361,2820.065154,2821.177167,2822.207484,2825.431396,2826.322482,2827.119795,2825.172857
1,139,1,Cook County,county,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",17,31,1414.571905,...,2035.841352,2055.126987,2076.534414,2100.626309,2122.413835,2142.564578,2153.740295,2157.310248,2154.482729,2147.400147
2,1090,2,Harris County,county,TX,TX,"Houston-The Woodlands-Sugar Land, TX",48,201,1179.817421,...,1597.663919,1603.149956,1612.142887,1616.414369,1616.730341,1608.047458,1607.559226,1606.469309,1609.155822,1602.519807
3,2402,3,Maricopa County,county,AZ,AZ,"Phoenix-Mesa-Chandler, AZ",4,13,927.513015,...,1758.931763,1769.286247,1778.064380,1781.073859,1777.505677,1774.508990,1771.448246,1766.625862,1762.638012,1756.104665
4,2841,4,San Diego County,county,CA,CA,"San Diego-Chula Vista-Carlsbad, CA",6,73,1650.148762,...,2933.815587,2940.423880,2957.204256,2965.278458,2973.988934,2982.511679,2987.581780,2993.645762,2990.922494,2987.463106

In [4]:
# make verbose output of datatypes
zori_county_wide.columns

Index(['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       'State', 'Metro', 'StateCodeFIPS', 'MunicipalCodeFIPS', '2015-01-31',
       ...
       '2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30', '2025-05-31',
       '2025-06-30', '2025-07-31', '2025-08-31', '2025-09-30', '2025-10-31'],
      dtype='object', length=139)

In [5]:
zori_county_wide.drop(columns=['RegionID', 'SizeRank', 'RegionType', 'StateName', 'Metro'], inplace=True)
zori_county_wide.columns

Index(['RegionName', 'State', 'StateCodeFIPS', 'MunicipalCodeFIPS',
       '2015-01-31', '2015-02-28', '2015-03-31', '2015-04-30', '2015-05-31',
       '2015-06-30',
       ...
       '2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30', '2025-05-31',
       '2025-06-30', '2025-07-31', '2025-08-31', '2025-09-30', '2025-10-31'],
      dtype='object', length=134)

In [6]:
# calculate fips
zori_county_wide['fips'] = zori_county_wide['StateCodeFIPS'] * 1000 + zori_county_wide['MunicipalCodeFIPS']

zori_county_wide.drop(columns=['StateCodeFIPS', 'MunicipalCodeFIPS'], inplace=True)

In [11]:
zori_county_wide.dtypes

2015-01-31     float64
2015-02-28     float64
2015-03-31     float64
2015-04-30     float64
2015-05-31     float64
                ...
2025-08-31     float64
2025-09-30     float64
2025-10-31     float64
fips             int64
region_name     object
Length: 132, dtype: object

In [10]:
zori_county_wide['region_name'] = zori_county_wide['RegionName'] + ", " + zori_county_wide['State']

# drop region name and state columns
zori_county_wide.drop(columns=['RegionName', 'State'], inplace=True)

zori_county_wide.head()

,2015-01-31,2015-02-28,2015-03-31,2015-04-30,2015-05-31,2015-06-30,2015-07-31,2015-08-31,2015-09-30,2015-10-31,...,2025-03-31,2025-04-30,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,fips,region_name
0,1710.142975,1722.166576,1738.077419,1753.138594,1769.546387,1780.649010,1793.598848,1802.643780,1815.583189,1820.400370,...,2826.578361,2820.065154,2821.177167,2822.207484,2825.431396,2826.322482,2827.119795,2825.172857,6037,"Los Angeles County, CA"
1,1414.571905,1423.546553,1434.978656,1443.981229,1454.368435,1464.665218,1470.028042,1472.848912,1467.573385,1459.513510,...,2076.534414,2100.626309,2122.413835,2142.564578,2153.740295,2157.310248,2154.482729,2147.400147,17031,"Cook County, IL"
2,1179.817421,1182.414718,1187.583813,1198.229681,1208.273757,1217.347958,1217.501916,1218.802403,1217.114570,1215.222152,...,1612.142887,1616.414369,1616.730341,1608.047458,1607.559226,1606.469309,1609.155822,1602.519807,48201,"Harris County, TX"
3,927.513015,942.475941,949.656045,962.904688,963.309904,971.214864,971.198668,972.477346,975.299218,977.807598,...,1778.064380,1781.073859,1777.505677,1774.508990,1771.448246,1766.625862,1762.638012,1756.104665,4013,"Maricopa County, AZ"
4,1650.148762,1660.975763,1669.601199,1672.781943,1683.499065,1692.248292,1708.535873,1719.399035,1727.778144,1730.941507,...,2957.204256,2965.278458,2973.988934,2982.511679,2987.581780,2993.645762,2990.922494,2987.463106,6073,"San Diego County, CA"

In [15]:
# Fix: Create the boolean mask or list separately
date_cols = [col for col in zori_county_wide.columns if col not in ['fips', 'region_name']]

date_cols_dt = pd.to_datetime(date_cols)

most_recent_date = date_cols_dt.max()
most_recent_col = most_recent_date.strftime('%Y-%m-%d')

# calculate one-year and five-year changes
one_year_date = most_recent_date - pd.DateOffset(years=1)
five_year_date = most_recent_date - pd.DateOffset(years=5)

# Find the closest matching columns for these dates
one_year_col = min(date_cols, key=lambda x: abs(pd.to_datetime(x) - one_year_date))
five_year_col = min(date_cols, key=lambda x: abs(pd.to_datetime(x) - five_year_date))

# Create the new dataframe
zori_county_clean = pd.DataFrame({
    'region_name': zori_county_wide['region_name'],
    'fips': zori_county_wide['fips'],
    'most_recent_date': most_recent_date,
    'most_recent_value': zori_county_wide[most_recent_col],
    'one_year_date': pd.to_datetime(one_year_col),
    'one_year_value': zori_county_wide[one_year_col],
    'one_year_change': ((zori_county_wide[most_recent_col] - zori_county_wide[one_year_col]) / zori_county_wide[one_year_col] * 100),
    'five_year_date': pd.to_datetime(five_year_col),
    'five_year_value': zori_county_wide[five_year_col],
    'five_year_change': ((zori_county_wide[most_recent_col] - zori_county_wide[five_year_col]) / zori_county_wide[five_year_col] * 100)
})

# Ensure proper data types
zori_county_clean['fips'] = zori_county_clean['fips'].astype(int)
zori_county_clean['region_name'] = zori_county_clean['region_name'].astype(str)

zori_county_clean.head()

,region_name,fips,most_recent_date,most_recent_value,one_year_date,one_year_value,one_year_change,five_year_date,five_year_value,five_year_change
0,"Los Angeles County, CA",6037,2025-10-31,2825.172857,2024-10-31,2758.994851,2.398627,2020-10-31,2229.203118,26.734654
1,"Cook County, IL",17031,2025-10-31,2147.400147,2024-10-31,2021.934078,6.205250,2020-10-31,1575.672860,36.284644
2,"Harris County, TX",48201,2025-10-31,1602.519807,2024-10-31,1602.126243,0.024565,2020-10-31,1320.302324,21.375217
3,"Maricopa County, AZ",4013,2025-10-31,1756.104665,2024-10-31,1768.513968,-0.701680,2020-10-31,1370.002387,28.182599
4,"San Diego County, CA",6073,2025-10-31,2987.463106,2024-10-31,2934.680324,1.798587,2020-10-31,2151.084477,38.881719

# II. Population and Centriods

### i. County Centriods

In [ ]:
import pandas as pd


# save county centroids data
county_centroids_url = "https://www2.census.gov/geo/docs/reference/cenpop2020/county/CenPop2020_Mean_CO.txt"
county_centroids = pd.read_csv(county_centroids_url)

   STATEFP  COUNTYFP  COUNAME   STNAME  POPULATION   LATITUDE  LONGITUDE  fips
0        1         1  Autauga  Alabama       58805  32.500194 -86.487813  1001
1        1         3  Baldwin  Alabama      231767  30.537396 -87.761478  1003
2        1         5  Barbour  Alabama       25223  31.843981 -85.301306  1005
3        1         7     Bibb  Alabama       22293  33.032236 -87.136826  1007
4        1         9   Blount  Alabama       59134  33.954604 -86.592667  1009

In [8]:
# create fips column
county_centroids['fips'] = county_centroids['STATEFP'] * 1000 + county_centroids['COUNTYFP']

# lowercase column names
county_centroids.columns = county_centroids.columns.str.lower()

county_centroids.head()

   statefp  countyfp  couname   stname  population   latitude  longitude  fips
0        1         1  Autauga  Alabama       58805  32.500194 -86.487813  1001
1        1         3  Baldwin  Alabama      231767  30.537396 -87.761478  1003
2        1         5  Barbour  Alabama       25223  31.843981 -85.301306  1005
3        1         7     Bibb  Alabama       22293  33.032236 -87.136826  1007
4        1         9   Blount  Alabama       59134  33.954604 -86.592667  1009

### ii. County population (2024)