In [19]:
import pandas as pd

# I. Get Zillow Data

### i. Counties

In [20]:
# checking if the county zillow link still works
county_wide_url = "https://files.zillowstatic.com/research/public_csvs/zori/County_zori_uc_sfrcondomfr_sm_month.csv?t=1734717130"

In [21]:
zori_county_wide = pd.read_csv(county_wide_url)

zori_county_wide.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,2015-01-31,...,2025-01-31,2025-02-28,2025-03-31,2025-04-30,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31
0,3101,0,Los Angeles County,county,CA,CA,"Los Angeles-Long Beach-Anaheim, CA",6,37,1710.142975,...,2779.603168,2802.865470,2826.578361,2820.065154,2821.177167,2822.207484,2825.431396,2826.322482,2827.119795,2825.172857
1,139,1,Cook County,county,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",17,31,1414.571905,...,2035.841352,2055.126987,2076.534414,2100.626309,2122.413835,2142.564578,2153.740295,2157.310248,2154.482729,2147.400147
2,1090,2,Harris County,county,TX,TX,"Houston-The Woodlands-Sugar Land, TX",48,201,1179.817421,...,1597.663919,1603.149956,1612.142887,1616.414369,1616.730341,1608.047458,1607.559226,1606.469309,1609.155822,1602.519807
3,2402,3,Maricopa County,county,AZ,AZ,"Phoenix-Mesa-Chandler, AZ",4,13,927.513015,...,1758.931763,1769.286247,1778.064380,1781.073859,1777.505677,1774.508990,1771.448246,1766.625862,1762.638012,1756.104665
4,2841,4,San Diego County,county,CA,CA,"San Diego-Chula Vista-Carlsbad, CA",6,73,1650.148762,...,2933.815587,2940.423880,2957.204256,2965.278458,2973.988934,2982.511679,2987.581780,2993.645762,2990.922494,2987.463106

In [22]:
# make verbose output of datatypes
zori_county_wide.columns

Index(['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       'State', 'Metro', 'StateCodeFIPS', 'MunicipalCodeFIPS', '2015-01-31',
       ...
       '2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30', '2025-05-31',
       '2025-06-30', '2025-07-31', '2025-08-31', '2025-09-30', '2025-10-31'],
      dtype='object', length=139)

In [23]:
zori_county_wide.drop(columns=['RegionID', 'SizeRank', 'RegionType', 'StateName', 'Metro'], inplace=True)
zori_county_wide.columns

Index(['RegionName', 'State', 'StateCodeFIPS', 'MunicipalCodeFIPS',
       '2015-01-31', '2015-02-28', '2015-03-31', '2015-04-30', '2015-05-31',
       '2015-06-30',
       ...
       '2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30', '2025-05-31',
       '2025-06-30', '2025-07-31', '2025-08-31', '2025-09-30', '2025-10-31'],
      dtype='object', length=134)

In [24]:
# calculate fips
zori_county_wide['fips'] = zori_county_wide['StateCodeFIPS'] * 1000 + zori_county_wide['MunicipalCodeFIPS']

zori_county_wide.drop(columns=['StateCodeFIPS', 'MunicipalCodeFIPS'], inplace=True)

In [25]:
zori_county_wide.dtypes

RegionName     object
State          object
2015-01-31    float64
2015-02-28    float64
2015-03-31    float64
               ...
2025-07-31    float64
2025-08-31    float64
2025-09-30    float64
2025-10-31    float64
fips            int64
Length: 133, dtype: object

In [26]:
zori_county_wide['region_name'] = zori_county_wide['RegionName'] + ", " + zori_county_wide['State']

# drop region name and state columns
zori_county_wide.drop(columns=['RegionName', 'State'], inplace=True)

zori_county_wide.head()

,2015-01-31,2015-02-28,2015-03-31,2015-04-30,2015-05-31,2015-06-30,2015-07-31,2015-08-31,2015-09-30,2015-10-31,...,2025-03-31,2025-04-30,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,fips,region_name
0,1710.142975,1722.166576,1738.077419,1753.138594,1769.546387,1780.649010,1793.598848,1802.643780,1815.583189,1820.400370,...,2826.578361,2820.065154,2821.177167,2822.207484,2825.431396,2826.322482,2827.119795,2825.172857,6037,"Los Angeles County, CA"
1,1414.571905,1423.546553,1434.978656,1443.981229,1454.368435,1464.665218,1470.028042,1472.848912,1467.573385,1459.513510,...,2076.534414,2100.626309,2122.413835,2142.564578,2153.740295,2157.310248,2154.482729,2147.400147,17031,"Cook County, IL"
2,1179.817421,1182.414718,1187.583813,1198.229681,1208.273757,1217.347958,1217.501916,1218.802403,1217.114570,1215.222152,...,1612.142887,1616.414369,1616.730341,1608.047458,1607.559226,1606.469309,1609.155822,1602.519807,48201,"Harris County, TX"
3,927.513015,942.475941,949.656045,962.904688,963.309904,971.214864,971.198668,972.477346,975.299218,977.807598,...,1778.064380,1781.073859,1777.505677,1774.508990,1771.448246,1766.625862,1762.638012,1756.104665,4013,"Maricopa County, AZ"
4,1650.148762,1660.975763,1669.601199,1672.781943,1683.499065,1692.248292,1708.535873,1719.399035,1727.778144,1730.941507,...,2957.204256,2965.278458,2973.988934,2982.511679,2987.581780,2993.645762,2990.922494,2987.463106,6073,"San Diego County, CA"

In [27]:
# Fix: Create the boolean mask or list separately
date_cols = [col for col in zori_county_wide.columns if col not in ['fips', 'region_name']]

date_cols_dt = pd.to_datetime(date_cols)

most_recent_date = date_cols_dt.max()
most_recent_col = most_recent_date.strftime('%Y-%m-%d')

# calculate one-year and five-year changes
one_year_date = most_recent_date - pd.DateOffset(years=1)
five_year_date = most_recent_date - pd.DateOffset(years=5)

# Find the closest matching columns for these dates
one_year_col = min(date_cols, key=lambda x: abs(pd.to_datetime(x) - one_year_date))
five_year_col = min(date_cols, key=lambda x: abs(pd.to_datetime(x) - five_year_date))

# Create the new dataframe
zori_county_clean = pd.DataFrame({
    'region_name': zori_county_wide['region_name'],
    'fips': zori_county_wide['fips'],
    'most_recent_date': most_recent_date,
    'most_recent_value': zori_county_wide[most_recent_col],
    'one_year_date': pd.to_datetime(one_year_col),
    'one_year_value': zori_county_wide[one_year_col],
    'one_year_change': ((zori_county_wide[most_recent_col] - zori_county_wide[one_year_col]) / zori_county_wide[one_year_col] * 100),
    'five_year_date': pd.to_datetime(five_year_col),
    'five_year_value': zori_county_wide[five_year_col],
    'five_year_change': ((zori_county_wide[most_recent_col] - zori_county_wide[five_year_col]) / zori_county_wide[five_year_col] * 100)
})

# Ensure proper data types
zori_county_clean['fips'] = zori_county_clean['fips'].astype(int)
zori_county_clean['region_name'] = zori_county_clean['region_name'].astype(str)

#increase all date cols one day
zori_county_clean['most_recent_date'] += pd.Timedelta(days=1)
zori_county_clean['one_year_date'] += pd.Timedelta(days=1)
zori_county_clean['five_year_date'] += pd.Timedelta(days=1)

zori_county_clean.head()

,region_name,fips,most_recent_date,most_recent_value,one_year_date,one_year_value,one_year_change,five_year_date,five_year_value,five_year_change
0,"Los Angeles County, CA",6037,2025-11-01,2825.172857,2024-11-01,2758.994851,2.398627,2020-11-01,2229.203118,26.734654
1,"Cook County, IL",17031,2025-11-01,2147.400147,2024-11-01,2021.934078,6.205250,2020-11-01,1575.672860,36.284644
2,"Harris County, TX",48201,2025-11-01,1602.519807,2024-11-01,1602.126243,0.024565,2020-11-01,1320.302324,21.375217
3,"Maricopa County, AZ",4013,2025-11-01,1756.104665,2024-11-01,1768.513968,-0.701680,2020-11-01,1370.002387,28.182599
4,"San Diego County, CA",6073,2025-11-01,2987.463106,2024-11-01,2934.680324,1.798587,2020-11-01,2151.084477,38.881719

# II. Population and Centriods

### i. County Centriods

In [ ]:
import pandas as pd


# save county centroids data
county_centroids_url = "https://www2.census.gov/geo/docs/reference/cenpop2020/county/CenPop2020_Mean_CO.txt"
county_centroids = pd.read_csv(county_centroids_url)

   STATEFP  COUNTYFP  COUNAME   STNAME  POPULATION   LATITUDE  LONGITUDE  fips
0        1         1  Autauga  Alabama       58805  32.500194 -86.487813  1001
1        1         3  Baldwin  Alabama      231767  30.537396 -87.761478  1003
2        1         5  Barbour  Alabama       25223  31.843981 -85.301306  1005
3        1         7     Bibb  Alabama       22293  33.032236 -87.136826  1007
4        1         9   Blount  Alabama       59134  33.954604 -86.592667  1009

In [8]:
# create fips column
county_centroids['fips'] = county_centroids['STATEFP'] * 1000 + county_centroids['COUNTYFP']

# lowercase column names
county_centroids.columns = county_centroids.columns.str.lower()

county_centroids.head()

   statefp  countyfp  couname   stname  population   latitude  longitude  fips
0        1         1  Autauga  Alabama       58805  32.500194 -86.487813  1001
1        1         3  Baldwin  Alabama      231767  30.537396 -87.761478  1003
2        1         5  Barbour  Alabama       25223  31.843981 -85.301306  1005
3        1         7     Bibb  Alabama       22293  33.032236 -87.136826  1007
4        1         9   Blount  Alabama       59134  33.954604 -86.592667  1009

### ii. Metros

In [135]:
cities = pd.read_csv('data/uscities.csv')

# form name column
cities['name'] = cities['city_ascii'] + ", " + cities['state_id']

# only necessary cols
cities = cities[['name', 'lat', 'lng']]

cities.head()

              name      lat       lng
0     New York, NY  40.6943  -73.9249
1  Los Angeles, CA  34.1141 -118.4068
2      Chicago, IL  41.8375  -87.6866
3        Miami, FL  25.7840  -80.2101
4      Houston, TX  29.7860  -95.3885

In [85]:
metro_url = "https://files.zillowstatic.com/research/public_csvs/zori/Metro_zori_uc_sfrcondomfr_sm_month.csv?t=1734717130"

zori_metro_wide = pd.read_csv(metro_url)

In [ ]:
index_cols = ['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName'] 

# melt df
zori_metro_long = pd.melt(
    zori_metro_wide,
    id_vars = index_cols,
    value_vars = [col for col in zori_metro_wide.columns if col not in index_cols],
    var_name = "date",
    value_name = "zori"
)

zori_metro_long['date'] = pd.to_datetime(zori_metro_long['date'])

# increase date by one day
zori_metro_long['date'] += pd.Timedelta(days=1)

zori_metro_long = zori_metro_long[['RegionName', 'date', 'zori']]

zori_metro_long.rename(columns={'RegionName': 'name'}, inplace=True)

# merge with cities to get lat/lon/population
zori_metro_long = pd.merge(zori_metro_long, cities, on='name', how='left')

# calculate 1-year and 5-year changes
zori_metro_long = zori_metro_long.sort_values(by=['name', 'date'])
zori_metro_long['one_year_change'] = zori_metro_long.groupby('name')['zori'].pct_change(periods=12) * 100
zori_metro_long['five_year_change'] = zori_metro_long.groupby('name')['zori'].pct_change(periods=60) * 100

# save the date of one year and five year comparisons
zori_metro_long['one_year_date'] = zori_metro_long['date'] - pd.DateOffset(years=1)
zori_metro_long['five_year_date'] = zori_metro_long['date'] - pd.DateOffset(years=5)

# read in rent_tracker/data/top_metros.json as a list
import json
with open('data/top_metros.json') as f:
    top_metros = json.load(f)
zori_metro_long = zori_metro_long[zori_metro_long['name'].isin(top_metros)]

zori_metro_long.to_csv('data/zori_metro_long.csv', index=False)

# make a df with most recent data only
most_recent_date = zori_metro_long['date'].max()
zori_metro_most_recent = zori_metro_long[zori_metro_long['date'] == most_recent_date]

/var/folders/jd/5wy1jytx2pg8j4jr12tl0k_m0000gq/T/ipykernel_47206/1666161514.py:26: FutureWarning: The default fill_method='ffill' in SeriesGroupBy.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  zori_metro_long['one_year_change'] = zori_metro_long.groupby('name')['zori'].pct_change(periods=12) * 100
/var/folders/jd/5wy1jytx2pg8j4jr12tl0k_m0000gq/T/ipykernel_47206/1666161514.py:27: FutureWarning: The default fill_method='ffill' in SeriesGroupBy.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  zori_metro_long['five_year_change'] = zori_metro_long.groupby('name')['zori'].pct_change(periods=60) * 100

In [137]:
zori_metro_most_recent[zori_metro_most_recent['name'] == 'Los Angeles, CA']

,name,date,zori,lat,lng,one_year_change,five_year_change,one_year_date,five_year_date
91334,"Los Angeles, CA",2025-11-01,2924.88411,34.1141,-118.4068,2.434086,29.759553,2024-11-01,2020-11-01

In [131]:
population_link = "https://www2.census.gov/programs-surveys/popest/tables/2020-2024/metro/totals/cbsa-met-est2024-pop.xlsx"

metros_pop = pd.read_excel(population_link, skiprows=3)
metros_pop['Unnamed: 0'] = metros_pop['Unnamed: 0'].str.lstrip('.')

# rename column
metros_pop = metros_pop.rename(columns={'Unnamed: 0': 'name'})

# remove rows where name doesn't contain "Metro Area"
metros_pop = metros_pop[metros_pop['name'].str.contains('Metro Area', na=False)]

# delete " Metro Area" from name column
metros_pop['name'] = metros_pop['name'].str.replace(' Metro Area', '', regex=False)

# clean up the name column
metros_pop['name'] = metros_pop['name'].apply(lambda x: x.split(',')[0].split('-')[0] + ',' + x.split(',')[1].split('-')[0])

metros_pop.drop(columns=['Unnamed: 1'], inplace=True)

# turn all col names to strings
metros_pop.columns = metros_pop.columns.map(str)

metros_pop = metros_pop[['name', '2024']].rename(columns={'2024': 'population'})

metros_pop

             name  population
2     Abilene, TX    184278.0
3       Akron, OH    702209.0
4      Albany, GA    145451.0
5      Albany, OR    132474.0
6      Albany, NY    913485.0
..            ...         ...
430   Arecibo, PR    180071.0
431   Guayama, PR     64546.0
432  Mayagüez, PR    207205.0
433     Ponce, PR    265039.0
434  San Juan, PR   2035484.0

[393 rows x 2 columns]

In [138]:
# merge with zori_metro_most_recent
zori_metro_most_recent = pd.merge(zori_metro_most_recent, metros_pop, on='name', how='left')

zori_metro_most_recent.head()

,name,date,zori,lat,lng,one_year_change,five_year_change,one_year_date,five_year_date,population
0,"Atlanta, GA",2025-11-01,1860.436723,33.7628,-84.4220,2.641010,31.916278,2024-11-01,2020-11-01,6411149.0
1,"Austin, TX",2025-11-01,1601.080204,30.3005,-97.7522,-3.082995,16.210586,2024-11-01,2020-11-01,2550637.0
2,"Baltimore, MD",2025-11-01,1920.850052,39.3051,-76.6144,2.759464,28.990486,2024-11-01,2020-11-01,2859024.0
3,"Birmingham, AL",2025-11-01,1375.024770,33.5279,-86.7971,2.165834,30.488340,2024-11-01,2020-11-01,1192583.0
4,"Boston, MA",2025-11-01,2916.591942,42.3188,-71.0852,2.994142,35.805527,2024-11-01,2020-11-01,5025517.0

In [134]:
metros_pop[metros_pop['name'] == 'Los Angeles, CA']

                name  population
226  Los Angeles, CA  12927614.0

# III. Homebuilding

In [145]:
import pandas as pd
from datetime import datetime, date
from dateutil.relativedelta import relativedelta
from typing import List
import re

In [146]:
def generate_year_month_range(end_date: date = None, years_back: int = 6) -> List[str]:
    """
    Generate a list of year-month combinations in 'yyyymm' format,
    starting from the specified end date and going back a specified number of years.

    Args:
        end_date (date, optional): The end date to start from. Defaults to today's date.
        years_back (int, optional): Number of years to go back. Defaults to 6.

    Returns:
        List[str]: List of year-month combinations in 'yyyymm' format, sorted in descending order.

    Example:
        >>> generate_year_month_range()  # If today is 2024-11-14
        ['202411', '202410', '202409', ..., '201812']
    """
    # If no end date is provided, use today's date
    if end_date is None:
        end_date = date.today()

    # Calculate start date
    start_date = end_date - relativedelta(years=years_back)

    # Initialize result list
    date_list = []

    # Current date for iteration
    current_date = end_date

    # Generate dates until we reach start date
    while current_date >= start_date:
        # Format date as 'yyyymm'
        date_str = current_date.strftime('%Y%m')
        date_list.append(date_str)
        # Move to previous month
        current_date -= relativedelta(months=1)

    return date_list

# Example usage
if __name__ == "__main__":
    date_list = generate_year_month_range()
    print(f"Generated {len(date_list)} year-month combinations:")
    print(date_list[:12])  # Print first year as example

Generated 73 year-month combinations:
['202511', '202510', '202509', '202508', '202507', '202506', '202505', '202504', '202503', '202502', '202501', '202412']

In [147]:
import time
import random
import requests
import pandas as pd

def check_url_exists(url):
    """Check if a URL exists without downloading the full file"""
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleBoxKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    try:
        response = requests.head(url, headers=headers, timeout=10)
        return response.status_code == 200
    except:
        return False

def process_2024_data(url, headers):
    """Process data from 2024 onwards"""
    df = pd.read_excel(url, skiprows=7, storage_options=headers)
    
    # Clean columns
    df.drop(columns=['Metro /Micro Code', 'Unnamed: 10'], inplace=True)
    
    # Clean column names and data
    df.columns = df.columns.str.replace('.1', '_ytd')
    df['Name'] = df['Name'].str.rstrip()
    
    # Add date - extract directly from URL
    date_part = url.split('_')[-1].replace('.xls', '')
    df['date'] = date_part
    
    return df

def process_2022_2023_data(url, headers):
    """Process data from 2022-2023"""
    df = pd.read_excel(url, skiprows=7, storage_options=headers)
    
    # Remove first row and clean columns
    df = df.iloc[1:]
    df.drop(columns=['Unnamed: 9'], inplace=True)
    
    # Clean column names and data
    df.columns = df.columns.str.replace('.1', '_ytd')
    df['Name'] = df['Name'].str.rstrip()
    
    # Add date - extract directly from URL
    date_part = url.split('_')[-1].replace('.xls', '')
    df['date'] = date_part
    
    return df

def process_pre_2022_data(url, headers):
    """Process data from 2021 and earlier"""
    df = pd.read_excel(url, skiprows=7, storage_options=headers)
    
    # Remove first row and clean columns
    df = df.iloc[1:]
    df.drop(columns=['Monthly Coverage Percent*', 'Unnamed: 10'], inplace=True)
    
    # Clean column names and data
    df.columns = df.columns.str.replace('.1', '_ytd')
    df['Name'] = df['Name'].str.rstrip()
    
    # Add date - extract directly from URL
    date_part = url.split('_')[-1].replace('.xls', '')
    df['date'] = date_part
    
    return df

# Initialize an empty list to store all dataframes
all_dfs = []

# Set up headers
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

# Process each date
for i, date_str in enumerate(date_list):
    year = int(date_str[:4])
    
    # Add delay between requests (2-4 seconds) to avoid rate limiting
    if i > 0:
        time.sleep(random.uniform(2, 4))
    
    try:
        # Determine URL format and processing function based on year
        if year >= 2024:
            url = f'https://www.census.gov/construction/bps/xls/cbsamonthly_{date_str}.xls'
            process_func = process_2024_data
        else:
            url = f'https://www.census.gov/construction/bps/xls/msamonthly_{date_str}.xls'
            if year >= 2022:
                process_func = process_2022_2023_data
            else:
                process_func = process_pre_2022_data
        
        # Check if URL exists
        if check_url_exists(url):
            try:
                df = process_func(url, headers)
                all_dfs.append(df)
                print(f"✓ Successfully processed data for {date_str}")
            except Exception as e:
                print(f"✗ Error processing {date_str}: {str(e)}")
                continue
        else:
            print(f"○ No data available for {date_str}")
            continue
            
    except Exception as e:
        print(f"✗ Error with {date_str}: {str(e)}")
        continue

# Concatenate all dataframes if we have any data
if all_dfs:
    homebuilding = pd.concat(all_dfs, ignore_index=True)
    
    # Convert date column to datetime
    homebuilding['date'] = pd.to_datetime(homebuilding['date'], format='%Y%m')
    
    # Sort by date and other relevant columns
    homebuilding = homebuilding.sort_values(['date', 'Name'], ascending=[False, True])
    
    print(f"\nFinal dataset contains {len(homebuilding)} rows from {len(all_dfs)} different months")
    print(f"Date range: {homebuilding['date'].min()} to {homebuilding['date'].max()}")
else:
    print("No data was successfully processed")
    homebuilding = pd.DataFrame()

○ No data available for 202511
○ No data available for 202510
○ No data available for 202509
✓ Successfully processed data for 202508
✓ Successfully processed data for 202507
✓ Successfully processed data for 202506
✓ Successfully processed data for 202505
✓ Successfully processed data for 202504
✓ Successfully processed data for 202503
✓ Successfully processed data for 202502
✓ Successfully processed data for 202501
✓ Successfully processed data for 202412
✓ Successfully processed data for 202411
✓ Successfully processed data for 202410
✓ Successfully processed data for 202409
✓ Successfully processed data for 202408
✓ Successfully processed data for 202407
✓ Successfully processed data for 202406
✓ Successfully processed data for 202405
✓ Successfully processed data for 202404
✓ Successfully processed data for 202403
✓ Successfully processed data for 202402
✓ Successfully processed data for 202401
✓ Successfully processed data for 202312
✓ Successfully processed data for 202311
✓ Successfully processed data for 202310
✓ Successfully processed data for 202309
✓ Successfully processed data for 202308
✓ Successfully processed data for 202307
✓ Successfully processed data for 202306
✓ Successfully processed data for 202305
✓ Successfully processed data for 202304
✓ Successfully processed data for 202303
✓ Successfully processed data for 202302
✓ Successfully processed data for 202301
✓ Successfully processed data for 202212
✓ Successfully processed data for 202211
✓ Successfully processed data for 202210
✓ Successfully processed data for 202209
✓ Successfully processed data for 202208
✓ Successfully processed data for 202207
✓ Successfully processed data for 202206
✓ Successfully processed data for 202205
✓ Successfully processed data for 202204
✓ Successfully processed data for 202203
✓ Successfully processed data for 202202
✓ Successfully processed data for 202201
✓ Successfully processed data for 202112
✓ Successfully processed data for 202111
✓ Successfully processed data for 202110
✓ Successfully processed data for 202109
✓ Successfully processed data for 202108
✓ Successfully processed data for 202107
✓ Successfully processed data for 202106
✓ Successfully processed data for 202105
✓ Successfully processed data for 202104
✓ Successfully processed data for 202103
✓ Successfully processed data for 202102
✓ Successfully processed data for 202101
✓ Successfully processed data for 202012
✓ Successfully processed data for 202011
✓ Successfully processed data for 202010
✓ Successfully processed data for 202009
✓ Successfully processed data for 202008
✓ Successfully processed data for 202007
✓ Successfully processed data for 202006
✓ Successfully processed data for 202005
✓ Successfully processed data for 202004
✓ Successfully processed data for 202003
✓ Successfully processed data for 202002
✓ Successfully processed data for 202001
✓ Successfully processed data for 201912
✓ Successfully processed data for 201911

Final dataset contains 37204 rows from 70 different months
Date range: 2019-11-01 00:00:00 to 2025-08-01 00:00:00

In [148]:
# clean up the name column
homebuilding['Name'] = homebuilding['Name'].apply(lambda x: x.split(',')[0].split('-')[0] + ',' + x.split(',')[1].split('-')[0])

homebuilding

,CSA,CBSA,Name,Total,1 Unit,2 Units,3 and 4 Units,5 Units or More,Num of Structures With 5 Units or More,Total_ytd,1 Unit_ytd,2 Units_ytd,3 and 4 Units_ytd,5 Units or More_ytd,Num of Structures With 5 Units or More_ytd,date
0,999.0,10100.0,"Aberdeen, SD",20.0,6.0,14.0,0.0,0.0,0.0,146.0,48.0,18.0,0.0,80.0,2.0,2025-08-01
1,999.0,10140.0,"Aberdeen, WA",23.0,21.0,2.0,0.0,0.0,0.0,171.0,164.0,4.0,3.0,0.0,0.0,2025-08-01
2,101.0,10180.0,"Abilene, TX",93.0,71.0,22.0,0.0,0.0,0.0,694.0,494.0,200.0,0.0,0.0,0.0,2025-08-01
3,999.0,10220.0,"Ada, OK",2.0,2.0,0.0,0.0,0.0,0.0,18.0,6.0,12.0,0.0,0.0,0.0,2025-08-01
4,220.0,10300.0,"Adrian, MI",14.0,14.0,0.0,0.0,0.0,0.0,122.0,103.0,0.0,4.0,15.0,3.0,2025-08-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37199,148.0,49340.0,"Worcester, MA",18.0,16.0,2.0,0.0,0.0,0.0,219.0,172.0,6.0,0.0,41.0,5.0,2019-11-01
37200,999.0,49420.0,"Yakima, WA",52.0,40.0,6.0,0.0,6.0,1.0,823.0,368.0,62.0,23.0,370.0,21.0,2019-11-01
37201,276.0,49620.0,"York, PA",11.0,7.0,0.0,4.0,0.0,0.0,155.0,96.0,6.0,11.0,42.0,3.0,2019-11-01
37202,566.0,49660.0,"Youngstown, OH",13.0,13.0,0.0,0.0,0.0,0.0,200.0,193.0,4.0,3.0,0.0,0.0,2019-11-01
37203,999.0,49740.0,"Yuma, AZ",80.0,80.0,0.0,0.0,0.0,0.0,1063.0,1057.0,6.0,0.0,0.0,0.0,2019-11-01

In [149]:
homebuilding = homebuilding[['Name', 'Total', '1 Unit', '2 Units', '3 and 4 Units',
       '5 Units or More', 'date']]
homebuilding['multi_total'] = homebuilding['2 Units'] + homebuilding['3 and 4 Units'] + homebuilding['5 Units or More']

/var/folders/jd/5wy1jytx2pg8j4jr12tl0k_m0000gq/T/ipykernel_47206/2794363686.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  homebuilding['multi_total'] = homebuilding['2 Units'] + homebuilding['3 and 4 Units'] + homebuilding['5 Units or More']

In [150]:
# lowercase columns
homebuilding.columns = homebuilding.columns.str.lower()

In [151]:
# Ensure the DataFrame is sorted by 'name' and 'date'
homebuilding = homebuilding.sort_values(by=['name', 'date'])

# Create a 12-month running total column
homebuilding['rt'] = (
    homebuilding.groupby('name')['total']
    .rolling(window=12, min_periods=1)
    .sum()
    .reset_index(level=0, drop=True)
)

# Create a 12-month running total column for multi-unit structures
homebuilding['multi_rt'] = (
    homebuilding.groupby('name')['multi_total']
    .rolling(window=12, min_periods=1)
    .sum()
    .reset_index(level=0, drop=True)
)

homebuilding.head()

,name,total,1 unit,2 units,3 and 4 units,5 units or more,date,multi_total,rt,multi_rt
17499,"Aberdeen, SD",2.0,2.0,0.0,0.0,0.0,2024-01-01,0.0,2.0,0.0
16578,"Aberdeen, SD",2.0,2.0,0.0,0.0,0.0,2024-02-01,0.0,4.0,0.0
15657,"Aberdeen, SD",4.0,4.0,0.0,0.0,0.0,2024-03-01,0.0,8.0,0.0
14736,"Aberdeen, SD",15.0,15.0,0.0,0.0,0.0,2024-04-01,0.0,23.0,0.0
13815,"Aberdeen, SD",1.0,1.0,0.0,0.0,0.0,2024-05-01,0.0,24.0,0.0

In [152]:
homebuilding = homebuilding[['name', 'date', 'rt', 'multi_rt']]

In [ ]:
# find the most recent date in homebuilding
most_recent_date = homebuilding['date'].max()

,name,date,zori,lat,lng,one_year_change,five_year_change,one_year_date,five_year_date,population,rt,multi_rt
0,"Atlanta, GA",2025-11-01,1860.436723,33.7628,-84.4220,2.641010,31.916278,2024-11-01,2020-11-01,6411149.0,NaN,NaN
1,"Austin, TX",2025-11-01,1601.080204,30.3005,-97.7522,-3.082995,16.210586,2024-11-01,2020-11-01,2550637.0,NaN,NaN
2,"Baltimore, MD",2025-11-01,1920.850052,39.3051,-76.6144,2.759464,28.990486,2024-11-01,2020-11-01,2859024.0,NaN,NaN
3,"Birmingham, AL",2025-11-01,1375.024770,33.5279,-86.7971,2.165834,30.488340,2024-11-01,2020-11-01,1192583.0,NaN,NaN
4,"Boston, MA",2025-11-01,2916.591942,42.3188,-71.0852,2.994142,35.805527,2024-11-01,2020-11-01,5025517.0,NaN,NaN

In [156]:
metros_pop

             name  population
2     Abilene, TX    184278.0
3       Akron, OH    702209.0
4      Albany, GA    145451.0
5      Albany, OR    132474.0
6      Albany, NY    913485.0
..            ...         ...
430   Arecibo, PR    180071.0
431   Guayama, PR     64546.0
432  Mayagüez, PR    207205.0
433     Ponce, PR    265039.0
434  San Juan, PR   2035484.0

[393 rows x 2 columns]

In [158]:
homebuilding.drop(columns=['population_x', 'population_y'], inplace=True)

In [159]:
# merge homebuilding with metros_pop
homebuilding = pd.merge(homebuilding, metros_pop, on='name', how='inner')

homebuilding

              name       date      rt  multi_rt  population
0      Abilene, TX 2019-11-01    23.0       2.0    184278.0
1      Abilene, TX 2019-12-01    60.0       8.0    184278.0
2      Abilene, TX 2020-01-01    89.0       8.0    184278.0
3      Abilene, TX 2020-02-01   119.0       8.0    184278.0
4      Abilene, TX 2020-03-01   148.0      10.0    184278.0
...            ...        ...     ...       ...         ...
25831     Yuma, AZ 2025-04-01  1413.0     358.0    220310.0
25832     Yuma, AZ 2025-05-01  1358.0     362.0    220310.0
25833     Yuma, AZ 2025-06-01  1257.0     321.0    220310.0
25834     Yuma, AZ 2025-07-01  1144.0     299.0    220310.0
25835     Yuma, AZ 2025-08-01  1109.0     293.0    220310.0

[25836 rows x 5 columns]

In [160]:
homebuilding['rt_pc'] = homebuilding['rt'] / homebuilding['population']
homebuilding['multi_rt_pc'] = homebuilding['multi_rt'] / homebuilding['population']


# change per capita columns to per 1000
for col in homebuilding.columns:
    if 'pc' in col:
        homebuilding[col] = homebuilding[col] * 1000

homebuilding

,name,date,rt,multi_rt,population,rt_pc,multi_rt_pc
0,"Abilene, TX",2019-11-01,23.0,2.0,184278.0,0.124811,0.010853
1,"Abilene, TX",2019-12-01,60.0,8.0,184278.0,0.325595,0.043413
2,"Abilene, TX",2020-01-01,89.0,8.0,184278.0,0.482966,0.043413
3,"Abilene, TX",2020-02-01,119.0,8.0,184278.0,0.645763,0.043413
4,"Abilene, TX",2020-03-01,148.0,10.0,184278.0,0.803134,0.054266
...,...,...,...,...,...,...,...
25831,"Yuma, AZ",2025-04-01,1413.0,358.0,220310.0,6.413690,1.624983
25832,"Yuma, AZ",2025-05-01,1358.0,362.0,220310.0,6.164042,1.643139
25833,"Yuma, AZ",2025-06-01,1257.0,321.0,220310.0,5.705597,1.457038
25834,"Yuma, AZ",2025-07-01,1144.0,299.0,220310.0,5.192683,1.357179
25835,"Yuma, AZ",2025-08-01,1109.0,293.0,220310.0,5.033816,1.329944

In [ ]:
region_map = {
    "New York, NY":"Northeast","Los Angeles, CA":"West","Chicago, IL":"Midwest",
    "Dallas, TX":"Southwest","Houston, TX":"Southwest","Atlanta, GA":"Southeast",
    "Washington, DC":"Northeast","Philadelphia, PA":"Northeast","Miami, FL":"Southeast",
    "Phoenix, AZ":"Southwest","Boston, MA":"Northeast","Riverside, CA":"West",
    "San Francisco, CA":"West","Detroit, MI":"Midwest","Seattle, WA":"West",
    "Minneapolis, MN":"Midwest","Tampa, FL":"Southeast","San Diego, CA":"West",
    "Denver, CO":"West","Baltimore, MD":"Northeast","Orlando, FL":"Southeast",
    "Charlotte, NC":"Southeast","St. Louis, MO":"Midwest","San Antonio, TX":"Southwest",
    "Portland, OR":"West","Austin, TX":"Southwest","Pittsburgh, PA":"Northeast",
    "Sacramento, CA":"West","Las Vegas, NV":"West","Cincinnati, OH":"Midwest",
    "Kansas City, MO":"Midwest","Columbus, OH":"Midwest","Indianapolis, IN":"Midwest",
    "Nashville, TN":"Southeast","Cleveland, OH":"Midwest","San Jose, CA":"West",
    "Virginia Beach, VA":"Southeast","Jacksonville, FL":"Southeast","Providence, RI":"Northeast",
    "Milwaukee, WI":"Midwest","Raleigh, NC":"Southeast","Oklahoma City, OK":"Southwest",
    "Louisville, KY":"Southeast","Richmond, VA":"Southeast","Memphis, TN":"Southeast",
    "Salt Lake City, UT":"West","Birmingham, AL":"Southeast","Grand Rapids, MI":"Midwest",
    "Buffalo, NY":"Northeast","Hartford, CT":"Northeast"
}