In [58]:
import json
import numpy as np
from matplotlib.pyplot import hexbin
import matplotlib.pyplot as plt

In [59]:
import pandas as pd
from nba_api.stats.endpoints import shotchartdetail
from nba_api.stats.static import players
import time
from datetime import datetime

In [60]:
from nba_api.stats.endpoints import shotchartleaguewide
import pandas as pd

def get_league_wide_shots(season='2025-26'):
    """
    Try to get all league shots in one API call using ShotChartLeagueWide
    """
    print(f"Fetching league-wide shot data for {season}...")
    
    try:
        shots = shotchartleaguewide.ShotChartLeagueWide(
            season_nullable=season,
            season_type_all_star='Regular Season',
            context_measure_simple='FGA'
        )
        
        df = shots.get_data_frames()[0]
        
        print(f"✓ Success! Retrieved {len(df):,} shots")
        print(f"✓ Unique players: {df.PLAYER_ID.nunique()}")
        print(f"✓ Unique games: {df.GAME_ID.nunique()}")
        
        print("\nColumns available:")
        print(df.columns.tolist())
        
        print("\nSample data:")
        print(df[['PLAYER_NAME', 'GAME_DATE', 'LOC_X', 'LOC_Y', 
                  'SHOT_DISTANCE', 'SHOT_MADE_FLAG']].head(10))
        
        # Save to CSV
        output_file = f'all_league_shots_{season}.csv'
        df.to_csv(output_file, index=False)
        print(f"\n✓ Saved to: {output_file}")
        
        return df
        
    except Exception as e:
        print(f"✗ Error: {e}")
        return None

# Execute it
shots_df = get_league_wide_shots(season='2025-26')

Fetching league-wide shot data for 2025-26...
✗ Error: ShotChartLeagueWide.__init__() got an unexpected keyword argument 'season_nullable'

In [61]:
shots_df = get_league_wide_shots(season='2025-26')

Fetching league-wide shot data for 2025-26...
✗ Error: ShotChartLeagueWide.__init__() got an unexpected keyword argument 'season_nullable'

In [62]:
from nba_api.stats.endpoints import shotchartleaguewide
import inspect

# See the function signature
print("ShotChartLeagueWide parameters:")
print(inspect.signature(shotchartleaguewide.ShotChartLeagueWide.__init__))

# Or get the docstring
print("\nDocstring:")
print(shotchartleaguewide.ShotChartLeagueWide.__doc__)

# Or check the source
print("\nSource code of __init__:")
print(inspect.getsource(shotchartleaguewide.ShotChartLeagueWide.__init__))

ShotChartLeagueWide parameters:
(self, league_id='00', season='2025-26', proxy=None, headers=None, timeout=30, get_request=True)

Docstring:
None

Source code of __init__:
    def __init__(
        self,
        league_id=LeagueID.default,
        season=Season.default,
        proxy=None,
        headers=None,
        timeout=30,
        get_request=True,
    ):
        self.proxy = proxy
        if headers is not None:
            self.headers = headers
        self.timeout = timeout
        self.parameters = {"LeagueID": league_id, "Season": season}
        if get_request:
            self.get_request()

In [63]:
from nba_api.stats.endpoints import shotchartleaguewide
import pandas as pd

def get_league_wide_shots(season='2025-26'):
    """
    Get all league shots in one API call using ShotChartLeagueWide
    """
    print(f"Fetching league-wide shot data for {season}...")
    
    try:
        shots = shotchartleaguewide.ShotChartLeagueWide(
            league_id='00',  # NBA
            season=season
        )
        
        df = shots.get_data_frames()[0]
        
        print(f"✓ Success! Retrieved {len(df):,} shots")
        print(f"✓ Unique players: {df.PLAYER_ID.nunique()}")
        print(f"✓ Unique games: {df.GAME_ID.nunique()}")
        
        print("\nColumns available:")
        print(df.columns.tolist())
        
        print("\nSample data:")
        print(df.head(10))
        
        # Save to CSV
        output_file = f'all_league_shots_{season}.csv'
        df.to_csv(output_file, index=False)
        print(f"\n✓ Saved to: {output_file}")
        
        return df
        
    except Exception as e:
        print(f"✗ Error: {e}")
        import traceback
        traceback.print_exc()
        return None

# Run it!
shots_df = get_league_wide_shots(season='2025-26')

Fetching league-wide shot data for 2025-26...
✓ Success! Retrieved 19 shots
✗ Error: 'DataFrame' object has no attribute 'PLAYER_ID'

Traceback (most recent call last):
  File "/var/folders/jd/5wy1jytx2pg8j4jr12tl0k_m0000gq/T/ipykernel_34096/626870341.py", line 19, in get_league_wide_shots
    print(f"✓ Unique players: {df.PLAYER_ID.nunique()}")
                               ^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'PLAYER_ID'

In [64]:
from nba_api.stats.endpoints import shotchartleaguewide
import pandas as pd

def get_league_wide_shots(season='2025-26', timeout=30, retries=10):
    """
    Get all league shots in one API call using ShotChartLeagueWide
    """
    print(f"Fetching league-wide shot data for {season}...")
    time.sleep(1)  # be polite to the API
    try:
        shots = shotchartleaguewide.ShotChartLeagueWide(
            league_id='00',
            season=season
        )
        
        # Check how many dataframes are returned
        dfs = shots.get_data_frames()
        print(f"✓ Number of dataframes returned: {len(dfs)}")
        
        # Look at each dataframe
        for i, df in enumerate(dfs):
            print(f"\n--- DataFrame {i} ---")
            print(f"Rows: {len(df)}")
            print(f"Columns: {df.columns.tolist()}")
            print(f"\nFirst few rows:")
            print(df.head())
            print("\n")
        
        return dfs
        
    except Exception as e:
        print(f"✗ Error: {e}")
        import traceback
        traceback.print_exc()
        return None

In [65]:
# get league wide shot chart data for 2025-26 season
shots_df = get_league_wide_shots(season='2025-26')

Fetching league-wide shot data for 2025-26...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 19
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE        SHOT_ZONE_BASIC         SHOT_ZONE_AREA  \
0  League Averages      Above the Break 3              Center(C)
1  League Averages      Above the Break 3   Left Side Center(LC)
2  League Averages      Above the Break 3  Right Side Center(RC)
3  League Averages              Backcourt         Back Court(BC)
4  League Averages  In The Paint (Non-RA)              Center(C)

   SHOT_ZONE_RANGE   FGA   FGM  FG_PCT
0          24+ ft.  2174   752   0.346
1          24+ ft.  3538  1250   0.353
2          24+ ft.  3054  1058   0.346
3  Back Court Shot     5     3   0.600
4         8-16 ft.  1682   761   0.452

In [66]:
seasons = [f"{y}-{str(y+1)[-2:]}" for y in range(1996, 2026)]  # 1996-97 .. 2025-26

In [67]:
# make a list to hold data
season_shots_list = []

# get league wide shots for each season
for season in seasons:
    shots = get_league_wide_shots(season=season)
    time.sleep(1)  # brief pause between calls
    season_shots_list.append(shots)

Fetching league-wide shot data for 1996-97...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

    FGA   FGM  FG_PCT
0    94     4   0.043
1  3143  1078   0.343
2  6847  2238   0.327
3  5215  1814   0.348
4   235     9   0.038


Fetching league-wide shot data for 1997-98...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

     FGA   FGM  FG_PCT
0    103     0   0.000
1   5406  1802   0.333
2  10122  3433   0.339
3  10064  3554   0.353
4    258    12   0.047


Fetching league-wide shot data for 1998-99...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

    FGA   FGM  FG_PCT
0    81     2   0.025
1  3354  1046   0.312
2  6170  2035   0.330
3  6485  2222   0.343
4   162     4   0.025


Fetching league-wide shot data for 1999-00...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

     FGA   FGM  FG_PCT
0    135     6   0.044
1   5768  1914   0.332
2   9946  3496   0.351
3  10215  3588   0.351
4    268     7   0.026


Fetching league-wide shot data for 2000-01...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 21
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages               None                   None             None
1  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
2  League Averages  Above the Break 3              Center(C)          24+ ft.
3  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
4  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.

     FGA   FGM  FG_PCT
0      2     1   0.500
1    118     5   0.042
2   5423  1849   0.341
3  10136  3504   0.346
4  10097  3592   0.356


Fetching league-wide shot data for 2001-02...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 21
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages               None                   None             None
1  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
2  League Averages  Above the Break 3              Center(C)          24+ ft.
3  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
4  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.

     FGA   FGM  FG_PCT
0     12     7   0.583
1    112     5   0.045
2   5704  1921   0.337
3  10930  3736   0.342
4  11133  3995   0.359


Fetching league-wide shot data for 2002-03...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

     FGA   FGM  FG_PCT
0    119     6   0.050
1   5825  2027   0.348
2  10735  3726   0.347
3  10707  3753   0.351
4    375     6   0.016


Fetching league-wide shot data for 2003-04...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

     FGA   FGM  FG_PCT
0    112     6   0.054
1   5759  1910   0.332
2  10870  3721   0.342
3  10655  3650   0.343
4    360     8   0.022


Fetching league-wide shot data for 2004-05...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

     FGA   FGM  FG_PCT
0    129     5   0.039
1   6275  2171   0.346
2  11825  4146   0.351
3  11282  3991   0.354
4    392     5   0.013


Fetching league-wide shot data for 2005-06...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

     FGA   FGM  FG_PCT
0    117     3   0.026
1   6428  2239   0.348
2  11851  4202   0.355
3  11574  4047   0.350
4    395    10   0.025


Fetching league-wide shot data for 2006-07...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

     FGA   FGM  FG_PCT
0    129     2   0.016
1   6700  2278   0.340
2  12488  4396   0.352
3  12172  4372   0.359
4    407    11   0.027


Fetching league-wide shot data for 2007-08...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

     FGA   FGM  FG_PCT
0    136     3   0.022
1   7334  2523   0.344
2  13443  4789   0.356
3  13094  4702   0.359
4    504    10   0.020


Fetching league-wide shot data for 2008-09...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 21
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages               None                   None             None
1  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
2  League Averages  Above the Break 3              Center(C)          24+ ft.
3  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
4  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.

     FGA   FGM  FG_PCT
0     28     9   0.321
1    114     4   0.035
2   7186  2543   0.354
3  13177  4784   0.363
4  13177  4774   0.362


Fetching league-wide shot data for 2009-10...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 21
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages               None                   None             None
1  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
2  League Averages  Above the Break 3              Center(C)          24+ ft.
3  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
4  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.

     FGA   FGM  FG_PCT
0     30    12   0.400
1     97     1   0.010
2   7520  2536   0.337
3  13276  4544   0.342
4  13586  4824   0.355


Fetching league-wide shot data for 2010-11...

KeyboardInterrupt:

In [68]:
# robustly concatenate the results in season_shots_list (handles lists-of-dfs, single dfs, Nones)
def _iter_dfs(obj):
    """Yield DataFrame objects from nested lists/tuples or single DataFrame; ignore other types."""
    if obj is None:
        return
    if isinstance(obj, pd.DataFrame):
        yield obj
    elif isinstance(obj, (list, tuple)):
        for item in obj:
            yield from _iter_dfs(item)
    else:
        return

dfs = [df for item in season_shots_list for df in _iter_dfs(item)]

if dfs:
    shots = pd.concat(dfs, ignore_index=True)
else:
    shots = pd.DataFrame()

shots

,GRID_TYPE,SHOT_ZONE_BASIC,SHOT_ZONE_AREA,SHOT_ZONE_RANGE,FGA,FGM,FG_PCT
0,League Averages,Above the Break 3,Back Court(BC),Back Court Shot,94,4,0.043
1,League Averages,Above the Break 3,Center(C),24+ ft.,3143,1078,0.343
2,League Averages,Above the Break 3,Left Side Center(LC),24+ ft.,6847,2238,0.327
3,League Averages,Above the Break 3,Right Side Center(RC),24+ ft.,5215,1814,0.348
4,League Averages,Backcourt,Back Court(BC),Back Court Shot,235,9,0.038
...,...,...,...,...,...,...,...
279,League Averages,Mid-Range,Right Side Center(RC),16-24 ft.,10771,4254,0.395
280,League Averages,Mid-Range,Right Side(R),8-16 ft.,9211,3664,0.398
281,League Averages,Mid-Range,Right Side(R),16-24 ft.,8233,3410,0.414
282,League Averages,Restricted Area,Center(C),Less Than 8 ft.,70879,42856,0.605
283,League Averages,Right Corner 3,Right Side(R),24+ ft.,6036,2360,0.391

In [69]:
# Loop seasons, add SEASON column, consolidate zones per season and combine results

def consolidate_shot_zones(df_in):
    """
    Calculate FGA and FGM for each basic zone, consolidating corner 3s.
    Expects columns: SHOT_ZONE_BASIC, FGA, FGM
    """
    df_local = df_in.copy()
    df_local['ZONE_CONSOLIDATED'] = df_local['SHOT_ZONE_BASIC'].replace({
        'Left Corner 3': 'Corner 3',
        'Right Corner 3': 'Corner 3'
    })
    consolidated = df_local.groupby('ZONE_CONSOLIDATED', as_index=False).agg({
        'FGA': 'sum',
        'FGM': 'sum'
    })
    return consolidated

seasons = [f"{y}-{str(y+1)[-2:]}" for y in range(1996, 2026)]  # 1996-97 .. 2025-26

season_consolidated_list = []

for season in seasons:
    print(f"Fetching season {season} ...")
    res = get_league_wide_shots(season=season)
    if res is None:
        print(f"  → no data for {season}, skipping")
        continue

    # handle function returning list of dfs or a single df
    if isinstance(res, list):
        if len(res) == 0:
            print(f"  → empty result list for {season}, skipping")
            continue
        df_season = res[0].copy()
    elif isinstance(res, pd.DataFrame):
        df_season = res.copy()
    else:
        print(f"  → unexpected return type for {season}: {type(res)}, skipping")
        continue

    # Ensure FGA/FGM exist
    if not {'FGA', 'FGM', 'SHOT_ZONE_BASIC'}.issubset(df_season.columns):
        print(f"  → required columns missing for {season}, skipping")
        continue

    df_season['SEASON'] = season
    consolidated = consolidate_shot_zones(df_season)
    consolidated['SEASON'] = season
    season_consolidated_list.append(consolidated)

# Combine all seasons
if season_consolidated_list:
    df = pd.concat(season_consolidated_list, ignore_index=True)
    # Optional: sort for readability
    df = df.sort_values(['SEASON', 'FGA'], ascending=[True, False]).reset_index(drop=True)
    print(f"\nCombined consolidated zones for {len(seasons)} seasons. Rows: {len(df)}")
else:
    df = pd.DataFrame()
    print("No season data consolidated.")

# Show result
df

Fetching season 1996-97 ...
Fetching league-wide shot data for 1996-97...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

    FGA   FGM  FG_PCT
0    94     4   0.043
1  3143  1078   0.343
2  6847  2238   0.327
3  5215  1814   0.348
4   235     9   0.038


Fetching season 1997-98 ...
Fetching league-wide shot data for 1997-98...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

     FGA   FGM  FG_PCT
0    103     0   0.000
1   5406  1802   0.333
2  10122  3433   0.339
3  10064  3554   0.353
4    258    12   0.047


Fetching season 1998-99 ...
Fetching league-wide shot data for 1998-99...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

    FGA   FGM  FG_PCT
0    81     2   0.025
1  3354  1046   0.312
2  6170  2035   0.330
3  6485  2222   0.343
4   162     4   0.025


Fetching season 1999-00 ...
Fetching league-wide shot data for 1999-00...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

     FGA   FGM  FG_PCT
0    135     6   0.044
1   5768  1914   0.332
2   9946  3496   0.351
3  10215  3588   0.351
4    268     7   0.026


Fetching season 2000-01 ...
Fetching league-wide shot data for 2000-01...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 21
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages               None                   None             None
1  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
2  League Averages  Above the Break 3              Center(C)          24+ ft.
3  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
4  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.

     FGA   FGM  FG_PCT
0      2     1   0.500
1    118     5   0.042
2   5423  1849   0.341
3  10136  3504   0.346
4  10097  3592   0.356


Fetching season 2001-02 ...
Fetching league-wide shot data for 2001-02...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 21
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages               None                   None             None
1  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
2  League Averages  Above the Break 3              Center(C)          24+ ft.
3  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
4  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.

     FGA   FGM  FG_PCT
0     12     7   0.583
1    112     5   0.045
2   5704  1921   0.337
3  10930  3736   0.342
4  11133  3995   0.359


Fetching season 2002-03 ...
Fetching league-wide shot data for 2002-03...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

     FGA   FGM  FG_PCT
0    119     6   0.050
1   5825  2027   0.348
2  10735  3726   0.347
3  10707  3753   0.351
4    375     6   0.016


Fetching season 2003-04 ...
Fetching league-wide shot data for 2003-04...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

     FGA   FGM  FG_PCT
0    112     6   0.054
1   5759  1910   0.332
2  10870  3721   0.342
3  10655  3650   0.343
4    360     8   0.022


Fetching season 2004-05 ...
Fetching league-wide shot data for 2004-05...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

     FGA   FGM  FG_PCT
0    129     5   0.039
1   6275  2171   0.346
2  11825  4146   0.351
3  11282  3991   0.354
4    392     5   0.013


Fetching season 2005-06 ...
Fetching league-wide shot data for 2005-06...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

     FGA   FGM  FG_PCT
0    117     3   0.026
1   6428  2239   0.348
2  11851  4202   0.355
3  11574  4047   0.350
4    395    10   0.025


Fetching season 2006-07 ...
Fetching league-wide shot data for 2006-07...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

     FGA   FGM  FG_PCT
0    129     2   0.016
1   6700  2278   0.340
2  12488  4396   0.352
3  12172  4372   0.359
4    407    11   0.027


Fetching season 2007-08 ...
Fetching league-wide shot data for 2007-08...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

     FGA   FGM  FG_PCT
0    136     3   0.022
1   7334  2523   0.344
2  13443  4789   0.356
3  13094  4702   0.359
4    504    10   0.020


Fetching season 2008-09 ...
Fetching league-wide shot data for 2008-09...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 21
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages               None                   None             None
1  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
2  League Averages  Above the Break 3              Center(C)          24+ ft.
3  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
4  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.

     FGA   FGM  FG_PCT
0     28     9   0.321
1    114     4   0.035
2   7186  2543   0.354
3  13177  4784   0.363
4  13177  4774   0.362


Fetching season 2009-10 ...
Fetching league-wide shot data for 2009-10...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 21
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages               None                   None             None
1  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
2  League Averages  Above the Break 3              Center(C)          24+ ft.
3  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
4  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.

     FGA   FGM  FG_PCT
0     30    12   0.400
1     97     1   0.010
2   7520  2536   0.337
3  13276  4544   0.342
4  13586  4824   0.355


Fetching season 2010-11 ...
Fetching league-wide shot data for 2010-11...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 21
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages               None                   None             None
1  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
2  League Averages  Above the Break 3              Center(C)          24+ ft.
3  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
4  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.

     FGA   FGM  FG_PCT
0     29    11   0.379
1     94     4   0.043
2   7027  2328   0.331
3  13263  4677   0.353
4  13192  4701   0.356


Fetching season 2011-12 ...
Fetching league-wide shot data for 2011-12...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 21
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages               None                   None             None
1  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
2  League Averages  Above the Break 3              Center(C)          24+ ft.
3  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
4  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.

     FGA   FGM  FG_PCT
0     20    11   0.550
1     64     1   0.016
2   5973  1971   0.330
3  11162  3796   0.340
4  11196  3907   0.349


Fetching season 2012-13 ...
Fetching league-wide shot data for 2012-13...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 21
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages               None                   None             None
1  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
2  League Averages  Above the Break 3              Center(C)          24+ ft.
3  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
4  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.

     FGA   FGM  FG_PCT
0     33     7   0.212
1     72     2   0.028
2   8133  2795   0.344
3  14414  5001   0.347
4  14958  5352   0.358


Fetching season 2013-14 ...
Fetching league-wide shot data for 2013-14...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 21
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages               None                   None             None
1  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
2  League Averages  Above the Break 3              Center(C)          24+ ft.
3  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
4  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.

     FGA   FGM  FG_PCT
0     49    14   0.286
1     71     4   0.056
2   9953  3524   0.354
3  15867  5642   0.356
4  15994  5603   0.350


Fetching season 2014-15 ...
Fetching league-wide shot data for 2014-15...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 21
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages               None                   None             None
1  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
2  League Averages  Above the Break 3              Center(C)          24+ ft.
3  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
4  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.

     FGA   FGM  FG_PCT
0     26    11   0.423
1     59     2   0.034
2  10430  3508   0.336
3  16574  5665   0.342
4  16363  5598   0.342


Fetching season 2015-16 ...
Fetching league-wide shot data for 2015-16...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 21
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages               None                   None             None
1  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
2  League Averages  Above the Break 3              Center(C)          24+ ft.
3  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
4  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.

     FGA   FGM  FG_PCT
0    166    50   0.301
1     62     5   0.081
2  11702  4010   0.343
3  17886  6230   0.348
4  16966  6008   0.354


Fetching season 2016-17 ...
Fetching league-wide shot data for 2016-17...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 21
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages               None                   None             None
1  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
2  League Averages  Above the Break 3              Center(C)          24+ ft.
3  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
4  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.

     FGA   FGM  FG_PCT
0    201    77   0.383
1     71     4   0.056
2  14055  4938   0.351
3  19853  6980   0.352
4  19503  6891   0.353


Fetching season 2017-18 ...
Fetching league-wide shot data for 2017-18...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

     FGA   FGM  FG_PCT
0     58     3   0.052
1  16206  5798   0.358
2  21857  7739   0.354
3  20755  7353   0.354
4    565     7   0.012


Fetching season 2018-19 ...
Fetching league-wide shot data for 2018-19...
✓ Number of dataframes returned: 1

--- DataFrame 0 ---
Rows: 20
Columns: ['GRID_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'FGA', 'FGM', 'FG_PCT']

First few rows:
         GRID_TYPE    SHOT_ZONE_BASIC         SHOT_ZONE_AREA  SHOT_ZONE_RANGE  \
0  League Averages  Above the Break 3         Back Court(BC)  Back Court Shot
1  League Averages  Above the Break 3              Center(C)          24+ ft.
2  League Averages  Above the Break 3   Left Side Center(LC)          24+ ft.
3  League Averages  Above the Break 3  Right Side Center(RC)          24+ ft.
4  League Averages          Backcourt         Back Court(BC)  Back Court Shot

     FGA   FGM  FG_PCT
0     48     3   0.063
1  17040  5834   0.342
2  24062  8467   0.352
3  23260  8175   0.351

         ZONE_CONSOLIDATED    FGA    FGM   SEASON
0                Mid-Range  79698  31993  1996-97
1          Restricted Area  74306  40703  1996-97
2    In The Paint (Non-RA)  23852  10333  1996-97
3        Above the Break 3  15299   5134  1996-97
4                 Corner 3   6149   2427  1996-97
..                     ...    ...    ...      ...
175        Restricted Area   7960   5343  2025-26
176  In The Paint (Non-RA)   5524   2411  2025-26
177               Corner 3   2803   1074  2025-26
178              Mid-Range   2713   1087  2025-26
179              Backcourt      5      3  2025-26

[180 rows x 4 columns]

In [70]:
# re-order columns for readability
df = df[['SEASON', 'ZONE_CONSOLIDATED', 'FGA', 'FGM']]

# rename columns
df.columns = ['Season', 'Zone', 'Attempts', 'Makes']

# calculate misses
df['Misses'] = df['Attempts'] - df['Makes']

# show result
df

/var/folders/jd/5wy1jytx2pg8j4jr12tl0k_m0000gq/T/ipykernel_34096/1475960797.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Misses'] = df['Attempts'] - df['Makes']

      Season                   Zone  Attempts  Makes  Misses
0    1996-97              Mid-Range     79698  31993   47705
1    1996-97        Restricted Area     74306  40703   33603
2    1996-97  In The Paint (Non-RA)     23852  10333   13519
3    1996-97      Above the Break 3     15299   5134   10165
4    1996-97               Corner 3      6149   2427    3722
..       ...                    ...       ...    ...     ...
175  2025-26        Restricted Area      7960   5343    2617
176  2025-26  In The Paint (Non-RA)      5524   2411    3113
177  2025-26               Corner 3      2803   1074    1729
178  2025-26              Mid-Range      2713   1087    1626
179  2025-26              Backcourt         5      3       2

[180 rows x 5 columns]

In [71]:
# print the df overview

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Season    180 non-null    object
 1   Zone      180 non-null    object
 2   Attempts  180 non-null    int64
 3   Makes     180 non-null    int64
 4   Misses    180 non-null    int64
dtypes: int64(3), object(2)
memory usage: 7.2+ KB
None

In [72]:
df['Zone'].unique()

array(['Mid-Range', 'Restricted Area', 'In The Paint (Non-RA)',
       'Above the Break 3', 'Corner 3', 'Backcourt'], dtype=object)

In [73]:
def pivot_zones_wide(df):
    """
    Convert long format to wide format with columns like:
    'Mid-Range Attempts', 'Mid-Range Makes', 'Mid-Range Misses', etc.
    """
    # Melt the numeric columns to create a long format first
    df_melted = df.melt(
        id_vars=['Season', 'Zone'],
        value_vars=['Attempts', 'Makes', 'Misses'],
        var_name='Metric',
        value_name='Value'
    )
    
    # Create new column names by combining Zone and Metric
    df_melted['Column'] = df_melted['Zone'] + ' ' + df_melted['Metric']
    
    # Pivot to wide format
    df_wide = df_melted.pivot(
        index='Season',
        columns='Column',
        values='Value'
    ).reset_index()
    
    # Sort columns alphabetically (optional)
    cols = ['Season'] + sorted([c for c in df_wide.columns if c != 'Season'])
    df_wide = df_wide[cols]
    
    return df_wide

# Apply the transformation
df_wide = pivot_zones_wide(df)

df_wide

Column,Season,Above the Break 3 Attempts,Above the Break 3 Makes,Above the Break 3 Misses,Backcourt Attempts,Backcourt Makes,Backcourt Misses,Corner 3 Attempts,Corner 3 Makes,Corner 3 Misses,In The Paint (Non-RA) Attempts,In The Paint (Non-RA) Makes,In The Paint (Non-RA) Misses,Mid-Range Attempts,Mid-Range Makes,Mid-Range Misses,Restricted Area Attempts,Restricted Area Makes,Restricted Area Misses
0,1996-97,15299,5134,10165,235,9,226,6149,2427,3722,23852,10333,13519,79698,31993,47705,74306,40703,33603
1,1997-98,25695,8789,16906,258,12,246,5933,2211,3722,28020,10416,17604,73521,28615,44906,66659,40077,26582
2,1998-99,16090,5305,10785,162,4,158,4599,1709,2890,18775,6816,11959,45678,17364,28314,37930,22544,15386
3,1999-00,26064,9004,17060,268,7,261,8349,3222,5127,31604,11790,19814,78892,31090,47802,61613,37519,24094
4,2000-01,25774,8950,16824,322,13,309,8573,3293,5280,31927,11791,20136,76947,30054,46893,59513,35646,23867
5,2001-02,27879,9657,18222,324,8,316,9168,3497,5671,29773,11487,18286,75634,29550,46084,61818,36692,25126
6,2002-03,27386,9512,17874,375,6,369,10086,3718,6368,30412,11862,18550,75728,29223,46505,62127,36720,25407
7,2003-04,27396,9287,18109,360,8,352,10258,3847,6411,28981,11163,17818,72162,27500,44662,63263,36759,26504
8,2004-05,29511,10313,19198,392,5,387,11654,4456,7198,27659,11022,16637,74227,29142,45085,67472,39454,28018
9,2005-06,29970,10491,19479,395,10,385,11961,4638,7323,27111,10996,16115,71316,28371,42945,67332,39982,27350
10,2006-07,31489,11048,20441,407,11,396,12598,4856,7742,26646,10993,15653,68885,27412,41473,68283,40950,27333
11,2007-08,34007,12017,21990,504,10,494,12966,5124,7842,27581,11287,16294,70404,28233,42171,68393,40931,27462
12,2008-09,33654,12105,21549,486,11,475,13605,5369,8236,27154,11241,15913,68070,27320,40750,69200,41187,28013
13,2009-10,34479,11905,22574,509,17,492,12733,4979,7754,28206,11941,16265,66911,26798,40113,70879,42856,28023
14,2010-11,33576,11710,21866,516,17,499,13110,5142,7968,32542,12668,19874,65681,26272,39409,66877,41306,25571
15,2011-12,28395,9675,18720,327,10,317,10641,3992,6649,25996,9925,16071,52783,20430,32353,56303,33976,22327
16,2012-13,37577,13150,24427,455,8,447,14516,5647,8869,31355,12115,19240,60849,23832,37017,70320,42476,27844
17,2013-14,41885,14773,27112,482,18,464,14547,5675,8872,32539,12803,19736,58505,23109,35396,70404,42859,27545
18,2014-15,43426,14773,28653,459,13,446,15371,5929,9442,32728,12808,19920,56822,22400,34422,70433,42317,28116
19,2015-16,46616,16253,30363,479,17,462,16421,6207,10214,32337,12912,19425,54412,21667,32745,71913,43245,28668
20,2016-17,53482,18813,34669,541,10,531,16801,6508,10293,31581,13242,18339,49167,19778,29389,71560,43719,27841
21,2017-18,58876,20893,37983,565,7,558,16711,6597,10114,35326,14003,21323,42733,17206,25527,71312,45023,26289
22,2018-19,64410,22479,41931,513,14,499,19102,7273,11829,37494,15093,22401,35532,14317,21215,76666,48198,28468
23,2019-20,59932,21055,38877,441,9,432,17820,6939,10881,32447,13003,19444,27112,11017,16095,64471,40974,23497
24,2020-21,61321,22077,39244,338,8,330,18929,7438,11491,36915,15793,21122,26891,11167,15724,61360,39366,21994
25,2021-22,68853,23838,45015,471,12,459,23034,8816,14218,42768,18347,24421,29703,12086,17617,66464,43470,22994
26,2022-23,66899,23680,43219,438,11,427,22461,8636,13825,45681,20293,25388,27678,11661,16017,68714,45729,22985
27,2023-24,67775,24345,43430,478,11,467,23577,9146,14431,45778,20150,25628,26321,11065,15256,68611,45421,23190
28,2024-25,72630,25660,46970,585,13,572,25153,9721,15432,47477,21053,26424,23143,9626,13517,64916,43036,21880
29,2025-26,8766,3060,5706,5,3,2,2803,1074,1729,5524,2411,3113,2713,1087,1626,7960,5343,2617

In [74]:
# restrict to only the season col and attempts cols
df_attempts_only = df_wide[['Season'] + [col for col in df_wide.columns if 'Attempts' in col]]

df_attempts_only.columns

# sort by distance
df_attempts_only = df_attempts_only[['Season', 'Restricted Area Attempts', 'In The Paint (Non-RA) Attempts',
                                   'Mid-Range Attempts', 'Corner 3 Attempts', 'Above the Break 3 Attempts', 'Backcourt Attempts']]

# rename columns for readability
df_attempts_only.columns = ['Season', 'Restricted Area', 'In The Paint (Non-RA)', 'Mid-Range', 'Corner 3', 'Above the Break 3', 'Backcourt']

df_attempts_only

,Season,Restricted Area,In The Paint (Non-RA),Mid-Range,Corner 3,Above the Break 3,Backcourt
0,1996-97,74306,23852,79698,6149,15299,235
1,1997-98,66659,28020,73521,5933,25695,258
2,1998-99,37930,18775,45678,4599,16090,162
3,1999-00,61613,31604,78892,8349,26064,268
4,2000-01,59513,31927,76947,8573,25774,322
5,2001-02,61818,29773,75634,9168,27879,324
6,2002-03,62127,30412,75728,10086,27386,375
7,2003-04,63263,28981,72162,10258,27396,360
8,2004-05,67472,27659,74227,11654,29511,392
9,2005-06,67332,27111,71316,11961,29970,395
10,2006-07,68283,26646,68885,12598,31489,407
11,2007-08,68393,27581,70404,12966,34007,504
12,2008-09,69200,27154,68070,13605,33654,486
13,2009-10,70879,28206,66911,12733,34479,509
14,2010-11,66877,32542,65681,13110,33576,516
15,2011-12,56303,25996,52783,10641,28395,327
16,2012-13,70320,31355,60849,14516,37577,455
17,2013-14,70404,32539,58505,14547,41885,482
18,2014-15,70433,32728,56822,15371,43426,459
19,2015-16,71913,32337,54412,16421,46616,479
20,2016-17,71560,31581,49167,16801,53482,541
21,2017-18,71312,35326,42733,16711,58876,565
22,2018-19,76666,37494,35532,19102,64410,513
23,2019-20,64471,32447,27112,17820,59932,441
24,2020-21,61360,36915,26891,18929,61321,338
25,2021-22,66464,42768,29703,23034,68853,471
26,2022-23,68714,45681,27678,22461,66899,438
27,2023-24,68611,45778,26321,23577,67775,478
28,2024-25,64916,47477,23143,25153,72630,585
29,2025-26,7960,5524,2713,2803,8766,5

In [75]:
df_attempts_only.to_csv('nba_shot_attempts_by_zone_wide.csv', index=False)