In [1]:
from nba_api.stats.endpoints import leaguegamefinder
import pandas as pd
import time
import config

In [4]:
pip install nfl_data_py

Requirement already satisfied: nfl_data_py in /Users/gabrielmelmed/git_repos/charts_gratia_chartis/venv/lib/python3.12/site-packages (0.3.3)
Requirement already satisfied: numpy<2.0,>=1.0 in /Users/gabrielmelmed/git_repos/charts_gratia_chartis/venv/lib/python3.12/site-packages (from nfl_data_py) (1.26.4)
Requirement already satisfied: pandas<2.0,>=1.0 in /Users/gabrielmelmed/git_repos/charts_gratia_chartis/venv/lib/python3.12/site-packages (from nfl_data_py) (1.5.3)
Requirement already satisfied: appdirs>1 in /Users/gabrielmelmed/git_repos/charts_gratia_chartis/venv/lib/python3.12/site-packages (from nfl_data_py) (1.4.4)
Requirement already satisfied: fastparquet>0.5 in /Users/gabrielmelmed/git_repos/charts_gratia_chartis/venv/lib/python3.12/site-packages (from nfl_data_py) (2024.11.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/gabrielmelmed/git_repos/charts_gratia_chartis/venv/lib/python3.12/site-packages (from pandas<2.0,>=1.0->nfl_data_py) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/gabrielmelmed/git_repos/charts_gratia_chartis/venv/lib/python3.12/site-packages (from pandas<2.0,>=1.0->nfl_data_py) (2025.2)
Requirement already satisfied: cramjam>=2.3 in /Users/gabrielmelmed/git_repos/charts_gratia_chartis/venv/lib/python3.12/site-packages (from fastparquet>0.5->nfl_data_py) (2.11.0)
Requirement already satisfied: fsspec in /Users/gabrielmelmed/git_repos/charts_gratia_chartis/venv/lib/python3.12/site-packages (from fastparquet>0.5->nfl_data_py) (2025.12.0)
Requirement already satisfied: packaging in /Users/gabrielmelmed/git_repos/charts_gratia_chartis/venv/lib/python3.12/site-packages (from fastparquet>0.5->nfl_data_py) (25.0)
Requirement already satisfied: six>=1.5 in /Users/gabrielmelmed/git_repos/charts_gratia_chartis/venv/lib/python3.12/site-packages (from python-dateutil>=2.8.1->pandas<2.0,>=1.0->nfl_data_py) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:
import nfl_data_py as nfl
import pandas as pd

# Import team descriptive information
teams = nfl.import_team_desc()

# The 'teams' DataFrame will contain various columns related to NFL teams,
# including unique identifiers. Common ID columns you might find are:
# - 'team_id': A unique identifier for the team.
# - 'team_abbr': The common abbreviation for the team (e.g., 'BUF', 'NE').
# - 'team_name': The full name of the team (e.g., 'Buffalo Bills', 'New England Patriots').

# To view the available columns and the first few rows of the data:
print(teams.head())

# To specifically extract a list of team IDs:
team_ids = teams['team_id'].tolist()
print("\nList of NFL Team IDs:")
print(team_ids)

# save team names and ids to json
teams[['team_id', 'team_name']].to_json('data/nfl_teams.json', orient='records', indent=4)

  team_abbr          team_name  team_id  team_nick team_conf team_division
0       ARI  Arizona Cardinals     3800  Cardinals       NFC      NFC West  \
1       ATL    Atlanta Falcons      200    Falcons       NFC     NFC South
2       BAL   Baltimore Ravens      325     Ravens       AFC     AFC North
3       BUF      Buffalo Bills      610      Bills       AFC      AFC East
4       CAR  Carolina Panthers      750   Panthers       NFC     NFC South

  team_color team_color2 team_color3 team_color4
0    #97233F     #000000     #ffb612     #a5acaf  \
1    #A71930     #000000     #a5acaf     #a30d2d
2    #241773     #9E7C0C     #9e7c0c     #c60c30
3    #00338D     #C60C30     #0c2e82     #d50a0a
4    #0085CA     #000000     #bfc0bf     #0085ca

                                 team_logo_wikipedia
0  https://upload.wikimedia.org/wikipedia/en/thum...  \
1  https://upload.wikimedia.org/wikipedia/en/thum...
2  https://upload.wikimedia.org/wikipedia/en/thum...
3  https://upload.wikimedia.org/wikipedia/en/thum...
4  https://upload.wikimedia.org/wikipedia/en/thum...

                                      team_logo_espn
0  https://a.espncdn.com/i/teamlogos/nfl/500/ari.png  \
1  https://a.espncdn.com/i/teamlogos/nfl/500/atl.png
2  https://a.espncdn.com/i/teamlogos/nfl/500/bal.png
3  https://a.espncdn.com/i/teamlogos/nfl/500/buf.png
4  https://a.espncdn.com/i/teamlogos/nfl/500-dark...

                                       team_wordmark
0  https://github.com/nflverse/nflverse-pbp/raw/m...  \
1  https://github.com/nflverse/nflverse-pbp/raw/m...
2  https://github.com/nflverse/nflverse-pbp/raw/m...
3  https://github.com/nflverse/nflverse-pbp/raw/m...
4  https://github.com/nflverse/nflverse-pbp/raw/m...

                                team_conference_logo
0  https://github.com/nflverse/nflverse-pbp/raw/m...  \
1  https://github.com/nflverse/nflverse-pbp/raw/m...
2  https://github.com/nflverse/nflverse-pbp/raw/m...
3  https://github.com/nflverse/nflverse-pbp/raw/m...
4  https://github.com/nflverse/nflverse-pbp/raw/m...

                                    team_league_logo
0  https://raw.githubusercontent.com/nflverse/nfl...  \
1  https://raw.githubusercontent.com/nflverse/nfl...
2  https://raw.githubusercontent.com/nflverse/nfl...
3  https://raw.githubusercontent.com/nflverse/nfl...
4  https://raw.githubusercontent.com/nflverse/nfl...

                                   team_logo_squared
0  https://github.com/nflverse/nflverse-pbp/raw/m...
1  https://github.com/nflverse/nflverse-pbp/raw/m...
2  https://github.com/nflverse/nflverse-pbp/raw/m...
3  https://github.com/nflverse/nflverse-pbp/raw/m...
4  https://github.com/nflverse/nflverse-pbp/raw/m...

List of NFL Team IDs:
[3800, 200, 325, 610, 750, 810, 920, 1050, 1200, 1400, 1540, 1800, 2120, 2200, 2250, 2310, 2510, 4400, 2510, 2520, 2700, 3000, 3200, 3300, 3410, 3430, 2520, 3700, 3900, 4400, 4600, 4500, 2510, 4900, 2100, 5110]

In [9]:
url = "https://raw.githubusercontent.com/djblechn-su/nba-player-team-ids/refs/heads/master/NBA_Team_IDs.csv"

# depulicate by "NBA_Current_Link_ID"
teams = pd.read_csv(url).drop_duplicates(subset=["NBA_Current_Link_ID"])

teams = teams[['BBRef_Team_Name', 'NBA_Current_Link_ID']]

teams.to_json('data/nba_teams.json', orient='records', indent=4)

In [8]:
from nba_api.stats.endpoints import teaminfocommon

# Get all teams.
teams_df = teaminfocommon.TeamInfoCommon(
    # all teams
    team_id=0
    ).get_data_frames()[0]

teams_df

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [10]:
import statsapi

In [12]:
# Get all MLB teams and their IDs
mlb_teams = statsapi.get('teams', {'sportIds': 1})['teams']

# Extract team names and IDs
team_data = [{'team_id': team['id'], 'team_name': team['name']} for team in mlb_teams]

# Convert to DataFrame
mlb_teams_df = pd.DataFrame(team_data)

# write to json
mlb_teams_df.to_json('data/mlb_teams.json', orient='records', indent=4)

In [19]:
pip install nhlpy

Collecting nhlpy
  Downloading nhlpy-0.3.0.tar.gz (2.2 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: nhlpy
  Building wheel for nhlpy (pyproject.toml) ... done
  Created wheel for nhlpy: filename=nhlpy-0.3.0-py3-none-any.whl size=4645 sha256=94f798dd5705b013fdd792e1fc5a3b40ad1e405f0195a72ece1b0a33a3b0fb6b
  Stored in directory: /Users/gabrielmelmed/Library/Caches/pip/wheels/76/dc/ef/a3c51291bcf2c2be27689fbb7d23d78cb23e79a151470a7281
Successfully built nhlpy
Installing collected packages: nhlpy
Successfully installed nhlpy-0.3.0
Note: you may need to restart the kernel to use updated packages.

In [9]:
import nhlpy

In [22]:
from nhlpy import NHLClient

client = NHLClient()

# Get all current teams
teams = client.teams.teams()

In [26]:
teams_df = pd.DataFrame(teams)
teams_df = teams_df[['name', 'franchise_id']]

teams_df.to_json('data/nhl_teams.json', orient='records', indent=4)

In [3]:
import pandas as pd

path = '/Users/gabrielmelmed/git_repos/charts_gratia_chartis/trifecta/data/raw/mlb/mlb_ny_new_york_yankees_games.csv'

df = pd.read_csv(path)

df

,game_id,game_datetime,game_date,game_type,status,away_name,home_name,away_id,home_id,doubleheader,...,venue_name,national_broadcasts,series_status,winning_team,losing_team,winning_pitcher,losing_pitcher,save_pitcher,summary,SEASON
0,3497,2000-04-04T02:35:00Z,2000-04-03,R,Final,New York Yankees,Anaheim Angels,147,108,N,...,Edison International Field,[],NYY leads 1-0,New York Yankees,Anaheim Angels,Orlando Hernandez,Ken Hill,Mariano Rivera,2000-04-03 - New York Yankees (3) @ Anaheim An...,2000
1,3292,2000-04-05T02:05:00Z,2000-04-04,R,Final,New York Yankees,Anaheim Angels,147,108,N,...,Edison International Field,[],NYY wins 2-0,New York Yankees,Anaheim Angels,Ramiro Mendoza,Troy Percival,Mariano Rivera,2000-04-04 - New York Yankees (5) @ Anaheim An...,2000
2,4975,2000-04-06T02:05:00Z,2000-04-05,R,Final,New York Yankees,Anaheim Angels,147,108,N,...,Edison International Field,[],NYY wins 2-1,Anaheim Angels,New York Yankees,Scott Schoeneweis,David Cone,NaN,2000-04-05 - New York Yankees (6) @ Anaheim An...,2000
3,5024,2000-04-08T02:05:00Z,2000-04-07,R,Final,New York Yankees,Seattle Mariners,147,136,N,...,Safeco Field,[],SEA leads 1-0,Seattle Mariners,New York Yankees,John Halama,Andy Pettitte,Kazuhiro Sasaki,2000-04-07 - New York Yankees (5) @ Seattle Ma...,2000
4,3415,2000-04-08T20:05:00Z,2000-04-08,R,Final,New York Yankees,Seattle Mariners,147,136,N,...,Safeco Field,[],Series tied 1-1,New York Yankees,Seattle Mariners,Jeff Nelson,Jose Mesa,Mariano Rivera,2000-04-08 - New York Yankees (3) @ Seattle Ma...,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5001,813065,2025-10-03T00:08:00Z,2025-10-02,F,Final,Boston Red Sox,New York Yankees,111,147,N,...,Yankee Stadium,"['ESPN Radio', 'ESPN']",NYY wins 2-1,New York Yankees,Boston Red Sox,Cam Schlittler,Connelly Early,NaN,2025-10-02 - Boston Red Sox (0) @ New York Yan...,2025
5002,813063,2025-10-04T20:08:00Z,2025-10-04,D,Final,New York Yankees,Toronto Blue Jays,147,141,N,...,Rogers Centre,"['ESPN Radio', 'FOX']",TOR leads 1-0,Toronto Blue Jays,New York Yankees,Kevin Gausman,Luis Gil,NaN,2025-10-04 - New York Yankees (1) @ Toronto Bl...,2025
5003,813062,2025-10-05T20:08:00Z,2025-10-05,D,Final,New York Yankees,Toronto Blue Jays,147,141,N,...,Rogers Centre,"['ESPN Radio', 'FS1']",TOR leads 2-0,Toronto Blue Jays,New York Yankees,Trey Yesavage,Max Fried,NaN,2025-10-05 - New York Yankees (7) @ Toronto Bl...,2025
5004,813061,2025-10-08T00:08:00Z,2025-10-07,D,Final,Toronto Blue Jays,New York Yankees,141,147,N,...,Yankee Stadium,"['ESPN Radio', 'FS1']",TOR leads 2-1,New York Yankees,Toronto Blue Jays,Tim Hill,Louis Varland,David Bednar,2025-10-07 - Toronto Blue Jays (6) @ New York ...,2025
5005,813060,2025-10-08T23:08:00Z,2025-10-08,D,Final,Toronto Blue Jays,New York Yankees,141,147,N,...,Yankee Stadium,"['ESPN Radio', 'FS1']",TOR wins 3-1,Toronto Blue Jays,New York Yankees,Seranthony Domínguez,Cam Schlittler,Jeff Hoffman,2025-10-08 - Toronto Blue Jays (5) @ New York ...,2025

In [4]:
# get value counts for `game_type`
df['game_type'].value_counts()

R    4239
S     562
D      86
L      67
W      29
E      14
F       9
Name: game_type, dtype: int64

In [7]:
df[df['game_type'] == 'E']

,game_id,game_datetime,game_date,game_type,status,away_name,home_name,away_id,home_id,doubleheader,...,venue_name,national_broadcasts,series_status,winning_team,losing_team,winning_pitcher,losing_pitcher,save_pitcher,summary,SEASON
723,243298,2004-03-28T10:00:00Z,2004-03-28,E,Final,???,???,147,241,N,...,Tokyo Dome,[],NaN,???,???,NaN,NaN,NaN,2004-03-28 - ??? () @ ??? () (Final),2004
724,243313,2004-03-29T03:00:00Z,2004-03-28,E,Final,???,???,147,341,N,...,Tokyo Dome,[],NaN,???,???,NaN,NaN,NaN,2004-03-28 - ??? () @ ??? () (Final),2004
725,243313,2004-03-29T03:00:00Z,2004-03-29,E,Final,???,???,147,341,N,...,Tokyo Dome,[],NaN,???,???,NaN,NaN,NaN,2004-03-29 - ??? () @ ??? () (Final),2004
728,243401,2004-04-04T17:15:00Z,2004-04-04,E,Final,New York Yankees Futures,New York Yankees,386,147,N,...,George M. Steinbrenner Field,[],NaN,New York Yankees,New York Yankees Futures,NaN,NaN,NaN,2004-04-04 - New York Yankees Futures () @ New...,2004
1499,237489,2008-03-18T19:00:00Z,2008-03-18,E,Final,New York Yankees,Virginia Tech Hokies,147,2293,N,...,English Field,[],NaN,New York Yankees,Virginia Tech Hokies,Jeff Karstens,Andrew Wells,NaN,2008-03-18 - New York Yankees (11) @ Virginia ...,2008
1681,257312,2009-03-03T18:15:00Z,2009-03-03,E,Final,United States,New York Yankees,940,147,N,...,George M. Steinbrenner Field,"['MLBN', 'MLB.TV']",USA leads 1-0,United States,New York Yankees,Roy Oswalt,Phil Hughes,Matt Lindstrom,2009-03-03 - United States (6) @ New York Yank...,2009
1683,257335,2009-03-05T18:15:00Z,2009-03-05,E,Final,Canada,New York Yankees,784,147,N,...,Tradition Field,[],NaN,Canada,New York Yankees,Scott Diamond,Joba Chamberlain,NaN,2009-03-05 - Canada (6) @ New York Yankees (0)...,2009
1926,279129,2010-04-03T17:05:00Z,2010-04-03,E,Final,New York Yankees Futures,New York Yankees,386,147,N,...,George M. Steinbrenner Field,[],NYY wins Exhibition,New York Yankees,New York Yankees Futures,Javier Vazquez,Jonathan Albaladejo,Jonathan Ortiz,2010-04-03 - New York Yankees Futures (6) @ Ne...,2010
2307,332096,2012-03-02T18:05:00Z,2012-03-02,E,Final,South Florida Bulls,New York Yankees,2292,147,N,...,George M. Steinbrenner Field,[],NYY wins Exhibition,New York Yankees,South Florida Bulls,Adam Warren,Matthew Reed,NaN,2012-03-02 - South Florida Bulls (0) @ New Yor...,2012
2519,363135,2013-03-06T18:05:00Z,2013-03-06,E,Final,Dominican Republic,New York Yankees,805,147,N,...,George M. Steinbrenner Field,['MLBN'],NaN,Dominican Republic,New York Yankees,Vidal Nuño,Cody Eppley,NaN,2013-03-06 - Dominican Republic (8) @ New York...,2013
2542,365671,2013-03-30T18:00:00Z,2013-03-30,E,Final,New York Yankees,Army Black Knights,147,4744,N,...,Johnson Stadium at Doubleday Field,[],NaN,New York Yankees,Army Black Knights,Vidal Nuño,Andrew Flaherty,NaN,2013-03-30 - New York Yankees (10) @ Army Blac...,2013
3309,509825,2017-03-08T18:05:00Z,2017-03-08,E,Final,Canada,New York Yankees,784,147,N,...,George M. Steinbrenner Field,[],NYY wins 1-0,New York Yankees,Canada,J.R. Graham,Shane Dawson,NaN,2017-03-08 - Canada (4) @ New York Yankees (10...,2017
4628,766493,2024-03-24T20:00:00Z,2024-03-24,E,Final,New York Yankees,Diablos Rojos del Mexico,147,532,N,...,Estadio Alfredo Harp Helu,['MLB.tv Free Game'],NaN,Diablos Rojos del Mexico,New York Yankees,Conner Menez,Tanner Tully,NaN,2024-03-24 - New York Yankees (3) @ Diablos Ro...,2024
4630,766494,2024-03-26T00:00:00Z,2024-03-25,E,Final,New York Yankees,Diablos Rojos del Mexico,147,532,N,...,Estadio Alfredo Harp Helu,['MLB.tv Free Game'],NaN,Diablos Rojos del Mexico,New York Yankees,Erick Leal,Luis Serna,Tomohiro Anraku,2024-03-25 - New York Yankees (5) @ Diablos Ro...,2024

In [8]:
# get the names of the files in /Users/gabrielmelmed/git_repos/charts_gratia_chartis/trifecta/data/raw/nfl
import os
files = os.listdir('/Users/gabrielmelmed/git_repos/charts_gratia_chartis/trifecta/data/raw/nfl')
files

['nfl_seattle_seattle_seahawks_games.csv',
 'nfl_cleveland_cleveland_browns_games.csv',
 'nfl_tennessee_tennessee_titans_games.csv',
 'nfl_bay_oakland_raiders_games.csv',
 'nfl_la_los_angeles_rams_games.csv',
 'nfl_north_carolina_carolina_panthers_games.csv',
 'nfl_ny_new_york_jets_games.csv',
 'nfl_detroit_detroit_lions_games.csv',
 'nfl_boston_new_england_patriots_games.csv',
 'nfl_dallas_dallas_cowboys_games.csv',
 'nfl_atlanta_atlanta_falcons_games.csv',
 'nfl_la_los_angeles_chargers_games.csv',
 'nfl_denver_denver_broncos_games.csv',
 'nfl_stl_st._louis_rams_games.csv',
 'nfl_pittsburgh_pittsburgh_steelers_games.csv',
 'nfl_miami_miami_dolphins_games.csv',
 'nfl_phoenix_arizona_cardinals_games.csv',
 'nfl_ny_new_york_giants_games.csv',
 'nfl_minneapolis_minnesota_vikings_games.csv',
 'nfl_houston_houston_texans_games.csv',
 'nfl_philadelphia_philadelphia_eagles_games.csv',
 'nfl_chicago_chicago_bears_games.csv',
 'nfl_wisconsin_green_bay_packers_games.csv',
 'nfl_tampa_tampa_bay_buccaneers_games.csv',
 'nfl_bay_san_francisco_49ers_games.csv',
 'nfl_dc_washington_commanders_games.csv']

In [15]:
files = os.listdir('/Users/gabrielmelmed/git_repos/charts_gratia_chartis/trifecta/data/raw/nba')

for file in files:
    # replace every between the last "_" and ".csv" with "games"
    new_file = file.rsplit('_', 1)[0] + '_games.csv'
    os.rename(os.path.join('/Users/gabrielmelmed/git_repos/charts_gratia_chartis/trifecta/data/raw/nba', file),
              os.path.join('/Users/gabrielmelmed/git_repos/charts_gratia_chartis/trifecta/data/raw/nba', new_file))

In [11]:
# read in trifecta/data/markets_teams.json
import json
with open('/Users/gabrielmelmed/git_repos/charts_gratia_chartis/trifecta/data/markets_teams.json') as f:
    markets_teams = json.load(f)

TypeError: string indices must be integers, not 'str'

In [ ]:
files = os.listdir('/Users/gabrielmelmed/git_repos/charts_gratia_chartis/trifecta/data/raw/nfl')

for file in files:
    # replace

In [17]:
os.chdir('/Users/gabrielmelmed/git_repos/charts_gratia_chartis')

In [19]:
df.columns

Index(['game_id', 'game_datetime', 'game_date', 'game_type', 'status',
       'away_name', 'home_name', 'away_id', 'home_id', 'doubleheader',
       'game_num', 'home_probable_pitcher', 'away_probable_pitcher',
       'home_pitcher_note', 'away_pitcher_note', 'away_score', 'home_score',
       'current_inning', 'inning_state', 'venue_id', 'venue_name',
       'national_broadcasts', 'series_status', 'winning_team', 'losing_team',
       'winning_pitcher', 'losing_pitcher', 'save_pitcher', 'summary',
       'SEASON', 'losing_Team'],
      dtype='object')

In [23]:
df['winning_team'].sample(100)

3303          Tampa Bay Rays
1329    Tampa Bay Devil Rays
1986          Tampa Bay Rays
1426          Tampa Bay Rays
255           Montreal Expos
                ...
2421          Tampa Bay Rays
4481          Boston Red Sox
3790          Tampa Bay Rays
546            Texas Rangers
3951    Washington Nationals
Name: winning_team, Length: 100, dtype: object

In [26]:
df = pd.read_csv('trifecta/data/raw/mlb/mlb_tampa_rays_games.csv')

df = df[['game_date', 'game_type', 'winning_team', 'losing_team']] 

df

       game_date game_type          winning_team           losing_team
0     2000-04-03         R  Tampa Bay Devil Rays       Minnesota Twins
1     2000-04-04         R       Minnesota Twins  Tampa Bay Devil Rays
2     2000-04-05         R       Minnesota Twins  Tampa Bay Devil Rays
3     2000-04-06         R  Tampa Bay Devil Rays       Minnesota Twins
4     2000-04-07         R     Cleveland Indians  Tampa Bay Devil Rays
...          ...       ...                   ...                   ...
4781  2025-09-24         R        Tampa Bay Rays     Baltimore Orioles
4782  2025-09-25         R     Baltimore Orioles        Tampa Bay Rays
4783  2025-09-26         R     Toronto Blue Jays        Tampa Bay Rays
4784  2025-09-27         R     Toronto Blue Jays        Tampa Bay Rays
4785  2025-09-28         R     Toronto Blue Jays        Tampa Bay Rays

[4786 rows x 4 columns]

In [30]:
df['winning_team'] = df['winning_team'].str.replace('Tampa Bay Devil Rays', 'Tampa Bay Rays', regex=False)
df['losing_team'] = df['losing_team'].str.replace('Tampa Bay Devil Rays', 'Tampa Bay Rays', regex=False)

df

       game_date game_type       winning_team        losing_team
0     2000-04-03         R     Tampa Bay Rays    Minnesota Twins
1     2000-04-04         R    Minnesota Twins     Tampa Bay Rays
2     2000-04-05         R    Minnesota Twins     Tampa Bay Rays
3     2000-04-06         R     Tampa Bay Rays    Minnesota Twins
4     2000-04-07         R  Cleveland Indians     Tampa Bay Rays
...          ...       ...                ...                ...
4781  2025-09-24         R     Tampa Bay Rays  Baltimore Orioles
4782  2025-09-25         R  Baltimore Orioles     Tampa Bay Rays
4783  2025-09-26         R  Toronto Blue Jays     Tampa Bay Rays
4784  2025-09-27         R  Toronto Blue Jays     Tampa Bay Rays
4785  2025-09-28         R  Toronto Blue Jays     Tampa Bay Rays

[4786 rows x 4 columns]

In [32]:
# drop rows where game_type is "E" or "S"
df = df[~df['game_type'].isin(['E', 'S'])]

In [34]:
df['game_date'] = pd.to_datetime(df['game_date'])

df

/var/folders/jd/5wy1jytx2pg8j4jr12tl0k_m0000gq/T/ipykernel_55941/1141866280.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['game_date'] = pd.to_datetime(df['game_date'])

      game_date game_type       winning_team        losing_team
0    2000-04-03         R     Tampa Bay Rays    Minnesota Twins
1    2000-04-04         R    Minnesota Twins     Tampa Bay Rays
2    2000-04-05         R    Minnesota Twins     Tampa Bay Rays
3    2000-04-06         R     Tampa Bay Rays    Minnesota Twins
4    2000-04-07         R  Cleveland Indians     Tampa Bay Rays
...         ...       ...                ...                ...
4781 2025-09-24         R     Tampa Bay Rays  Baltimore Orioles
4782 2025-09-25         R  Baltimore Orioles     Tampa Bay Rays
4783 2025-09-26         R  Toronto Blue Jays     Tampa Bay Rays
4784 2025-09-27         R  Toronto Blue Jays     Tampa Bay Rays
4785 2025-09-28         R  Toronto Blue Jays     Tampa Bay Rays

[4230 rows x 4 columns]

In [59]:
import json
from pathlib import Path

# Get the current working directory (already set to charts_gratia_chartis in cell 19)
script_dir = Path.cwd()

# Load markets_teams.json
with open(script_dir / "trifecta" / "data" / "markets_teams.json") as f:
    markets_data = json.load(f)

In [61]:
from anyio import Path
import pandas as pd
import os
import sys
from pathlib import Path


mlb_teams = []
for market in markets_data['markets_teams']:
    for team in market['teams']:
        if team['league'] == 'MLB':
            mlb_teams.append({
                'market': market['market'],
                'name': team['name'].replace(' ', '_').lower(),
                'api_id': team['api_id'],
                'abbr': team['abbr'],
                'full_name': team['full_name']
            })

def clean_mlb_data(df):
    """Clean MLB data."""
    # Select relevant columns
    df = df[['game_date', 'game_type', 'winning_team', 'losing_team']].copy()

    # Standardize team names
    df['winning_team'] = df['winning_team'].str.replace('Tampa Bay Devil Rays', 'Tampa Bay Rays', regex=False)
    df['losing_team'] = df['losing_team'].str.replace('Tampa Bay Devil Rays', 'Tampa Bay Rays', regex=False)
    df['winning_team'] = df['winning_team'].str.replace('Florida Marlins', 'Miami Marlins', regex=False)
    df['losing_team'] = df['losing_team'].str.replace('Florida Marlins', 'Miami Marlins', regex=False)
    df['winning_team'] = df['winning_team'].str.replace('Cleveland Indians', 'Cleveland Guardians', regex=False)
    df['losing_team'] = df['losing_team'].str.replace('Cleveland Indians', 'Cleveland Guardians', regex=False) 
    
    # Drop exhibition and spring training games
    df = df[~df['game_type'].isin(['E', 'S'])]
    
    # Convert game_date to datetime
    df['game_date'] = pd.to_datetime(df['game_date'])
    # rename game_date to date
    df = df.rename(columns={'game_date': 'date'})
    
    return df



for i in mlb_teams:
    market = i['market'].lower()
    team_name = i['name'].lower()
    team_abbr = i['abbr']
    team_full_name = i['full_name']

    input_file = script_dir.parent / "charts_gratia_chartis" / "trifecta" / "data" / "raw" / "mlb" / f"mlb_{market}_{team_name}_games.csv"
    print(f"\n{'='*60}")
    print(f"Processing data for {team_full_name}")
    if not input_file.exists():
        print(f"Input file {input_file} does not exist. Skipping.")
        continue
    
    df = pd.read_csv(input_file)
    df_cleaned = clean_mlb_data(df)

============================================================
Processing data for New York Yankees

============================================================
Processing data for New York Mets

============================================================
Processing data for Los Angeles Dodgers

============================================================
Processing data for Chicago White Sox

============================================================
Processing data for Chicago Cubs

============================================================
Processing data for Texas Rangers

============================================================
Processing data for Oakland Athletics

============================================================
Processing data for San Francisco Giants

============================================================
Processing data for Washington Nationals

============================================================
Processing data for Boston Red Sox

============================================================
Processing data for Philadelphia Phillies

============================================================
Processing data for Miami Marlins

============================================================
Processing data for Atlanta Braves

============================================================
Processing data for Detroit Tigers

============================================================
Processing data for Cleveland Guardians

============================================================
Processing data for Pittsburgh Pirates

============================================================
Processing data for Minnesota Twins

============================================================
Processing data for Milwaukee Brewers

============================================================
Processing data for St. Louis Cardinals

============================================================
Processing data for Tampa Bay Rays

============================================================
Processing data for Colorado Rockies

============================================================
Processing data for Seattle Mariners

============================================================
Processing data for Houston Astros

============================================================
Processing data for Arizona Diamondbacks

============================================================
Processing data for Toronto Blue Jays

In [62]:
df = pd.read_csv("trifecta/data/raw/mlb/mlb_ny_yankees_games.csv")

df = clean_mlb_data(df)

In [63]:
df

           date game_type       winning_team        losing_team
0    2000-04-03         R   New York Yankees     Anaheim Angels
1    2000-04-04         R   New York Yankees     Anaheim Angels
2    2000-04-05         R     Anaheim Angels   New York Yankees
3    2000-04-07         R   Seattle Mariners   New York Yankees
4    2000-04-08         R   New York Yankees   Seattle Mariners
...         ...       ...                ...                ...
5001 2025-10-02         F   New York Yankees     Boston Red Sox
5002 2025-10-04         D  Toronto Blue Jays   New York Yankees
5003 2025-10-05         D  Toronto Blue Jays   New York Yankees
5004 2025-10-07         D   New York Yankees  Toronto Blue Jays
5005 2025-10-08         D  Toronto Blue Jays   New York Yankees

[4430 rows x 4 columns]

In [65]:
df['yankees_win'] = (df['winning_team'] == 'New York Yankees').astype(int)

In [66]:
ny_wins = df[['date', 'yankees_win']]

ny_wins

           date  yankees_win
0    2000-04-03            1
1    2000-04-04            1
2    2000-04-05            0
3    2000-04-07            0
4    2000-04-08            1
...         ...          ...
5001 2025-10-02            1
5002 2025-10-04            0
5003 2025-10-05            0
5004 2025-10-07            1
5005 2025-10-08            0

[4430 rows x 2 columns]

In [67]:
df = pd.read_csv("/Users/gabrielmelmed/git_repos/charts_gratia_chartis/trifecta/data/raw/nhl/nhl_bay_sharks_games.csv")

df

,game_date,home_team_abbr,away_team_abbr,home_score,away_score,SEASON
0,2000-10-06,SJS,STL,1.0,4.0,20002001
1,2000-10-12,SJS,PHX,2.0,1.0,20002001
2,2000-10-14,SJS,BOS,5.0,2.0,20002001
3,2000-10-18,DAL,SJS,2.0,1.0,20002001
4,2000-10-20,MIN,SJS,1.0,3.0,20002001
...,...,...,...,...,...,...
2288,2026-04-09,ANA,SJS,NaN,NaN,20252026
2289,2026-04-11,SJS,VAN,NaN,NaN,20252026
2290,2026-04-13,NSH,SJS,NaN,NaN,20252026
2291,2026-04-15,CHI,SJS,NaN,NaN,20252026
2292,2026-04-16,WPG,SJS,NaN,NaN,20252026

In [68]:
# drop rows where home_score or away_score is NaN
df = df.dropna(subset=['home_score', 'away_score'])

df

,game_date,home_team_abbr,away_team_abbr,home_score,away_score,SEASON
0,2000-10-06,SJS,STL,1.0,4.0,20002001
1,2000-10-12,SJS,PHX,2.0,1.0,20002001
2,2000-10-14,SJS,BOS,5.0,2.0,20002001
3,2000-10-18,DAL,SJS,2.0,1.0,20002001
4,2000-10-20,MIN,SJS,1.0,3.0,20002001
...,...,...,...,...,...,...
2237,2025-12-01,SJS,UTA,6.0,3.0,20252026
2238,2025-12-03,SJS,WSH,1.0,7.0,20252026
2239,2025-12-05,DAL,SJS,4.0,1.0,20252026
2240,2025-12-07,CAR,SJS,1.0,4.0,20252026
2241,2025-12-09,PHI,SJS,4.0,1.0,20252026

In [69]:
df.columns

Index(['game_date', 'home_team_abbr', 'away_team_abbr', 'home_score',
       'away_score', 'SEASON'],
      dtype='object')

In [74]:
# make a winner column based on home_score and away_score

df['winning_team'] = df.apply(lambda row: row['home_team_abbr'] if row['home_score'] > row['away_score'] else row['away_team_abbr'], axis=1)

df = df.rename(columns={'game_date': 'date'})
df['date'] = pd.to_datetime(df['date'])

df

,date,home_team_abbr,away_team_abbr,home_score,away_score,SEASON,winning_team
0,2000-10-06,SJS,STL,1.0,4.0,20002001,STL
1,2000-10-12,SJS,PHX,2.0,1.0,20002001,SJS
2,2000-10-14,SJS,BOS,5.0,2.0,20002001,SJS
3,2000-10-18,DAL,SJS,2.0,1.0,20002001,DAL
4,2000-10-20,MIN,SJS,1.0,3.0,20002001,SJS
...,...,...,...,...,...,...,...
2237,2025-12-01,SJS,UTA,6.0,3.0,20252026,SJS
2238,2025-12-03,SJS,WSH,1.0,7.0,20252026,WSH
2239,2025-12-05,DAL,SJS,4.0,1.0,20252026,DAL
2240,2025-12-07,CAR,SJS,1.0,4.0,20252026,SJS
2241,2025-12-09,PHI,SJS,4.0,1.0,20252026,PHI

In [ ]:
df = pd.read_csv("trifecta/data/raw/nfl/nfl_bay_raiders_games.csv")

df = df[['gameday','game_type','home_team', 'away_team', 'home_score', 'away_score']]

df['winning_team'] = df.apply(lambda row: row['home_team'] if row['home_score'] > row['away_score'] else row['away_team'], axis=1)

df

        gameday game_type home_team away_team  home_score  away_score
0    2000-09-03       REG       OAK        SD         9.0         6.0
1    2000-09-10       REG       IND       OAK        31.0        38.0
2    2000-09-17       REG       OAK       DEN        24.0        33.0
3    2000-09-24       REG       OAK       CLE        36.0        10.0
4    2000-10-08       REG        SF       OAK        28.0        34.0
..          ...       ...       ...       ...         ...         ...
323  2019-12-01       REG        KC       OAK        40.0         9.0
324  2019-12-08       REG       OAK       TEN        21.0        42.0
325  2019-12-15       REG       OAK       JAX        16.0        20.0
326  2019-12-22       REG       LAC       OAK        17.0        24.0
327  2019-12-29       REG       DEN       OAK        16.0        15.0

[328 rows x 6 columns]

In [76]:
df.columns

Index(['game_id', 'season', 'game_type', 'week', 'gameday', 'weekday',
       'gametime', 'away_team', 'away_score', 'home_team', 'home_score',
       'location', 'result', 'total', 'overtime', 'old_game_id', 'gsis',
       'nfl_detail_id', 'pfr', 'pff', 'espn', 'ftn', 'away_rest', 'home_rest',
       'away_moneyline', 'home_moneyline', 'spread_line', 'away_spread_odds',
       'home_spread_odds', 'total_line', 'under_odds', 'over_odds', 'div_game',
       'roof', 'surface', 'temp', 'wind', 'away_qb_id', 'home_qb_id',
       'away_qb_name', 'home_qb_name', 'away_coach', 'home_coach', 'referee',
       'stadium_id', 'stadium'],
      dtype='object')

In [80]:
df[['gameday','game_type','home_team', 'away_team', 'home_score', 'away_score']]

        gameday game_type home_team away_team  home_score  away_score
0    2000-09-03       REG       OAK        SD         9.0         6.0
1    2000-09-10       REG       IND       OAK        31.0        38.0
2    2000-09-17       REG       OAK       DEN        24.0        33.0
3    2000-09-24       REG       OAK       CLE        36.0        10.0
4    2000-10-08       REG        SF       OAK        28.0        34.0
..          ...       ...       ...       ...         ...         ...
323  2019-12-01       REG        KC       OAK        40.0         9.0
324  2019-12-08       REG       OAK       TEN        21.0        42.0
325  2019-12-15       REG       OAK       JAX        16.0        20.0
326  2019-12-22       REG       LAC       OAK        17.0        24.0
327  2019-12-29       REG       DEN       OAK        16.0        15.0

[328 rows x 6 columns]

In [81]:
df['game_type'].value_counts()

REG    320
DIV      3
CON      2
WC       2
SB       1
Name: game_type, dtype: int64